product = [{
    "id": 0,
    "title": "",
    "Price": "",
    "keyFeatures": "",
    "image": "",
}, {
    "id": 1,
    "title": "Dawlance Air Conditioner Frost Inverter 30 DC Inverter 1.5 Ton Split AC Cool Only 14000 BTU",
    "Price": " 170,500.",
    "keyFeatures": "12 Years Compressor Warranty, 4 Years Card Warranty, Auto Restart, Hidden LED Display, Timer, Indoor Unit Cooling Operating Range (° C) 17 ~ 32,Gold Fin, EER = 3.01, Air Flow Rate m3/hr = 835, Sleep mode, Removable/ Washable Panel, Self Diagnosis, Turbo Mode,  Memory Function, Anti-Rust Outdoor Casing,   Moisture removal L/h:1.5,   Voltage Range 150 - 240",
    "image": "https://surmawala.pk/media/amasty/webp/catalog/product/cache/be98501646b05c02f36d7a80a701adca/f/r/frost-30new.webp",
}, {
    "id": 2,
    "title": "Dawlance Air Conditioner Frost Inverter 20 DC Inverter 1.25 Ton Split AC Cool Only 14000 BTU",
    "Price": " 157000.",
    "keyFeatures": "12 Years Compressor Warranty, 4 Years Card Warranty, Auto Restart, Hidden LED Display, Timer, Indoor Unit Cooling Operating Range (° C) 17 ~ 32,Gold Fin, EER = 3.01, Air Flow Rate m3/hr = 835, Sleep mode, Removable/ Washable Panel, Self Diagnosis, Turbo Mode,  Memory Function, Anti-Rust Outdoor Casing,   Moisture removal L/h:1.5,   Voltage Range 150 - 240",
    "image": "http://127.0.0.1:5501/Img/d2.jpg",
}, {
    "id": 3,
    "title": "Dawlance 1.5 Ton Normal Split Air Conditioner Extreme 30 - 18000 BTU",
    "Price": " 163,000.",
    "keyFeatures": "3 Years Compressor Warranty,Refrigerant (Gas): R-410a,Compressor Type: Non-Inverter, Product Type: Cool Only, Capacity:1.5 ton,Fan Speed: 5, 4-Way Air Flow: Yes,Fin Coating Type - (Indoor/Outdoor): Gold Fin, Air Flow Rate m3/hr = 835, Self Cleaning: Yes, Auto-Restart Function: Yes, Sleep Mode: Yes,",
    "image": "http://127.0.0.1:5501/Img/d3.jpg",
}, {
    "id": 4,
    "title": "Dawlance Inverter AC 1.5 Ton Enercon 30",
    "Price": " 147,000.",
    "keyFeatures": "12 Years Compressor Warranty, Long Throw, Voltage Range 150 260 V, Comfort,Heat & Cool, Auto Restart, Hidden Display, Multiple Programming Feature (Timer) 24 hours, Sleep Mode, Indoor Unit Cooling Operating Range (° C) 17-32, Gold Fin Condenser,",
    "image": "https://static-01.daraz.pk/p/6a9ada41f95fda247cc1dc4c13e2cf9a.png",
}, {
    "id": 5,
    "title": "Dawlance Inverter AC 1 Ton Sprinter 15",
    "Price": " 147,000.",
    "keyFeatures": "12 years Brand Warranty, Quick Cooling Long Air Throw, Refrigerant Leakage Detection, Fire Proof Control Box, Corrosion & Rust Free With Gold Fin, High-Efficiency Tubing, Heat & Cool Function, Low Voltage Startup (150-260V), Indoor Unit Cooling Operating Range (° C) 17-32, Gold Fin Condenser",
    "image": "https://estore.zahidbrothers.com/wp-content/uploads/2023/06/dawlance-sprinter-15-inverter-air-conditioner-1200x1200.webp",
}, {
    "id": 6,
    "title": "HAIER HSU-18HJ (G) 1.5 Ton Puri Inverter AC",
    "Price": " 205,000.",
    "keyFeatures": "10 years Brand Warranty, Air Conditioner Capacity 1.5 Tons (18000 BTU),Air Conditioner Features Auto Cleaning, Heat and Cool, Low Voltage Operation, Twin Rotary Compressor, Wi-Fi and Auto Clean, Air Conditioner Type Split Air Conditioner, Compressor Type Tropicalized Compressor, Color Golden, Heat & Cool Function, Technology Inverter, Air Purification, Super IFD Filter, Wide Voltage Range With Hyper PCB",
    "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTiK7E-X6FJb0bJG3hGeIEtoCyu78C_kQBS8VjWsPdSqA&s",
}, {
    "id": 7,
    "title": "Haier HSU-18HJUV/013WUSDC(G) 1.5-Ton Triple Inverter AC",
    "Price": " 190,000.",
    "keyFeatures": "Haier HSU-18HJUV – 1.5 Ton DC Inverter Air Conditioner, Wall Mounted, Golden Color, UV Light Generator, Smart Wi-Fi Control, Self Cleaning, General Parameter Capacity(Ton): 1.5 Ton, Type: DC Inverter, Cooling Capacity(BTU): 18000, Heating Capacity(BTU): 1800, Air Circulation(m3/ h): 1100, Power input(W) Cooling: 1720(450 - 2300), Power Input(W) Heating: 1760(450 - 2350)",
    "image": "https://www.aysonline.pk/wp-content/uploads/2022/06/ezgif.com-gif-maker-2.jpg",
}, {
    "id": 8,
    "title": "HAIER SPLIT AC HSU 18HFTCD T-3 (W)",
    "Price": " 190,000.",
    "keyFeatures": "Warranty 10 Years Compressor, Air Conditioner Capacity 1.5 Tons (18000 BTU), Air Conditioner Features Auto Cleaning, Heat and Cool, Low Voltage Operation, Twin Rotary Compressor, Air Conditioner Type Split Air Conditioner, Compressor Type T3 Compressor, Technology Full DC Inverter AC, Color White, 1.5 Ton, Fixed or inverter:DC Inverter, Category wise: DC Inverter, Type: Wall Mount, Display: Hidden LED, Refrigerant: R32, Refrigerant pipe: Liq Side: 6mm, Gas side: 12mm",
    "image": "https://cubeonline.pk/cdn/shop/files/W020230718518643659051_1024x1024.jpg?v=1690780498",
}, {
    "id": 9,
    "title": "Haier HSU-18HFCM 1.5 Ton DC Inverter AC",
    "Price": " 146,000.",
    "keyFeatures": "General Parameters, Ton: 1.5 Ton, Fixed or inverter: DC Inverter, Cooling Capacity(BTU): 19000, Heating Capacity(BTU): 19500, Air Circulation（m³/h）: 850, Power Input(W)-Cooling: 410 ~ 2200, Power Input(W)-Heating: 420 ~ 2250, Running Current(A)-Cooling: 2.3 ~10.2, Running Current(A)-Heating: 2.4 ~10.3, Power Supply (Ph/V/Hz): 1/220/50",
    "image": "https://lahorelectronics.com/wp-content/uploads/2021/05/hsu-18hfcf.jpg",
}, {
    "id": 10,
    "title": "Haier HSU-12HFAD DC Inverter AC 1 Ton",
    "Price": " 122,000.",
    "keyFeatures": "A-PAM Technology, Turbo Cooling & Heating, 46C Full BTU, Easy Installation, One-Touch Cleaning, UPS Inverter, WiFi Smart, Cooling Capacity(BTU): 13000, Heating Capacity(BTU): 13500, Air Circulation（m³/h）: 700, Power Input(W)-Heating: 450 ~ 1450, Running Current(A)-Cooling: 2.6 ~ 6.6, Running Current(A)-Heating: 2.6 ~ 6.7",
    "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRo6-7KAio4_FzGppJvGcMLZmcRwGHbX1VWtnmAmH1FMw&s",
}, {
    "id": 11,
    "title": "Dawlance CF-91998 Inverter Twin Door Deep Freezer Signature Grey",
    "Price": " 101,000.",
    "keyFeatures": "12-Years Warranty, Width: 138.5 cm & Height: 90 cm, 16 Cubic Feet Capacity, Inverter Technology, Sleek Silver Design, Chest Freezer Type, Horizontal Twin Doors, Touch Display Included, Secure Door Lock, Interior Freezer Light",
    "image": "https://www.aysonline.pk/wp-content/uploads/2023/11/91998.png",
}, {
    "id": 12,
    "title": "Dawlance 91998-H GD Signature Inverter Deep Freezer",
    "Price": " 128,000.",
    "keyFeatures": "12-Years Warranty, 12 Year Compressor Warranty, 55% Energy Saving Due To Inverter And R600a, Stucoo Diamond Sheet, Quick Freeze Button, Low Voltage, Scratch Less Glass Top, Inverter Technology, LED Light, Door LED Light-Freezer",
    "image": "http://127.0.0.1:5501/Img/fd2.png",
}, {
    "id": 13,
    "title": "Dawlance Inverter Deep Freezer 91998 Signature GD 385 Liters",
    "Price": " 111,000.",
    "keyFeatures": "12 Year Compressor Warranty, 385 Liters, Upto 55% energy saving, Dimensions (W x D x H) mm: 1385 x 775 x 880, Cooling Technology: Static, Double Door, Scratchless Glass Top Design, Handle Type: External, LED Top Light, Consumes less than 2 energy savers, Quick Freeze Button",
    "image": "https://www.aysonline.pk/wp-content/uploads/2021/12/91998-CHECKER.jpg.webp",
}, {
    "id": 14,
    "title": "Dawlance Deep Freezer CF-91997 LVS",
    "Price": " 92,000.",
    "keyFeatures": "10 Year Compressor Warranty, Color Champagne, Grey, White, Deep Freezer Capacity 451 to 550 liters, Deep Freezer Cubic feet 15 Cubic feet, Deep Freezer Type Chest, Number of Doors 2 doors, Compressor Type Tropicalized Compressor, Stucco Diamond sheet for Clean Interior, Quick Freeze Button for fastest cooling, Low voltage Start-up (No Need for Stabilizer), Up to 35% energy saving",
    "image": "https://bismillahelectronics.pk/wp-content/uploads/2022/03/double-door-3-768x488-1.jpg",
}, {
    "id": 15,
    "title": "Dawlance Deep Freezer DF-500 Double Door 418 Liters",
    "Price": " 97,500.",
    "keyFeatures": "10 Year Compressor Warranty, 418 Liters, Dimensions (WxDx H) mm: 1334 x 721 x 870, Cooling Technology: Static, Double Door – Single Cabinet, LED Top Light, Longest Cooling retention upto 5 days, Upto 45% Energy Saving, Easily Convertible From Freezer to Refrigerator, One-Touch Quick Freeze, 5- Way Evaporator for Faster Cooling, Series: Hybrid Cooling",
    "image": "https://www.aysonline.pk/wp-content/uploads/2021/07/df500.png",
}, {
    "id": 16,
    "title": "Haier Inverter Deep Freezer HDF-545INV 19.26 Cubic Feet",
    "Price": " 123,000.",
    "keyFeatures": "10 Year Compressor Warranty, 545 Liters, Dimensions (HxWxD mm): 905x1654x745, 19.26 Cubic Feet, Compressor: Inverter, Balance Cooling, Super Freeze Function, Ref & DF Adjustable, Type: Chest Freezer, 105V – 260V, Refrigerant: R600a, Copper Evaporator: 5 sides, Super Freeze Function, Power On Indicator",
    "image": "https://www.aysonline.pk/wp-content/uploads/2019/12/Haier-Freezer-HDF-545DD-Resize-Resize-600x600.jpg.webp",
}, {
    "id": 17,
    "title": "Haier Deep Freezer HDF-545DD 19.26 Cubic Feet",
    "Price": " 115,500.",
    "keyFeatures": "Warranty 3 year compressor, 10 Year Compressor Warranty, 545 Liters, Dimensions (HxWxD mm): 905x1654x745, 19.26 Cubic Feet, Compressor: Inverter, Balance Cooling, Super Freeze Function, Ref & DF Adjustable, Type: Chest Freezer, 105V – 260V, Refrigerant: R600a, Copper Evaporator: 5 sides, Super Freeze Function, Power On Indicator",
    "image": "https://shandaarbuy.pk/cdn/shop/products/545_1-2_2c760ef2-3469-46b2-bd98-e5469c786fef_large.png?v=1702393997",
}, {
    "id": 18,
    "title": "Haier Deep Freezer HDF-405SD 14.31 Cubic Feet",
    "Price": " 89,000.",
    "keyFeatures": "Warranty 3 year compressor, 10 Year Compressor Warranty, 405 Liters, Dimensions (HxWxD mm): 895x1242x745, 14.31 Cubic Feet, Compressor: Inverter, Balance Cooling, Super Freeze Function, Ref & DF Adjustable, Type: Chest Freezer, 160V – 260V, Refrigerant: R600a, Copper Evaporator: 5 sides, Super Freeze Function, Power On Indicator",
    "image": "https://www.ezziel.com/wp-content/uploads/2020/05/Haier-inverter-Deep-Freezer-HDF-405-inv-2.png",
}, {
    "id": 19,
    "title": "Haier Deep Freezer HDF-385H 13.60 Cubic Feet",
    "Price": " 88,000.",
    "keyFeatures": "Warranty 3 year compressor, 10 Year Compressor Warranty, 385 Liters, Dimensions (HxWxD mm): 895x1242x745, 13.60 Cubic Feet, Compressor: Inverter, Balance Cooling, Super Freeze Function, Ref & DF Adjustable, Type: Chest Freezer, 160V – 260V, Refrigerant: R600a, Copper Evaporator: 5 sides, Super Freeze Function, Power On Indicator",
    "image": "https://www.aysonline.pk/wp-content/uploads/2019/10/haier-385-l-double-door-deep-freezer-hdf-385h-image1-1-600x600.jpg",
}, {
    "id": 20,
    "title": "Haier Deep Freezer HDF-245SD 8.66 Cubic Feet",
    "Price": " 69,000.",
    "keyFeatures": "Warranty 3 year compressor, 10 Year Compressor Warranty, 245 Liters, Dimensions (HxWxD mm): 895x720x745, 8.66 Cubic Feet, Compressor: Inverter, Balance Cooling, Super Freeze Function, Ref & DF Adjustable, Type: Chest Freezer, 160V – 260V, Refrigerant: R600a, Copper Evaporator: 4 sides, Super Freeze Function, Power On Indicator",
    "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTbAT87rZeUzVJmym85lqo9VNWsRIrCuAfRUfoUJ2itEQ&s",
}, {
    "id": 21,
    "title": "Dawlance Top Mount Refrigerator 91999 AVANTE PLus GD Inverter - 20CFT/560Ltr",
    "Price": " 152,500.",
    "keyFeatures": "Warranty: 12 Years Compressor, Warranty: 1-Year Parts, Upto 35% Energy Saving, Works On as Low as 135V (No Need for Stabilizer), Modern Door Handle design, Anti-fungal Removable Gasket, Wider and Deeper Body Design, No. of Doo Double Door, Refrigerant: R-600A, Cooling Features: Direct Cool, Shelf Material: Toughened Wire Shelves, Shelf Material (Freezer): Toughened Wire Shelves",
    "image": "https://salmanelectronics.com/wp-content/uploads/2022/11/91999-IOT.webp",
}, {
    "id": 22,
    "title": "Dawlance 438ltr/15.46cft Refrigerator 9193 WB AVANTE Plus Inverter GD",
    "Price": " 136,600.",
    "keyFeatures": "Warranty: 12 Years Compressor, Warranty: 1-Year Parts, Upto 35% Energy Saving, Works On as Low as 135V (No Need for Stabilizer), Modern Door Handle design, Anti-fungal Removable Gasket, Wider and Deeper Body Design, No. of Doo Double Door, Refrigerant: R-600A, Cooling Features: Direct Cool, Shelf Material: Toughened Wire Shelves, Shelf Material (Freezer): Toughened Wire Shelves",
    "image": "https://static-01.daraz.pk/p/e58207af397893e020b958bc182eb07a.png",
}, {
    "id": 23,
    "title": "Dawlance Glass Door AVANTE+ GB Inverter Refrigerator 15 cu ft (9191-WB)",
    "Price": " 132,500.",
    "keyFeatures": "Warranty: 12 Years Compressor, Warranty: 1-Year Parts, Upto 35% Energy Saving, Works On as Low as 135V (No Need for Stabilizer), Modern Door Handle design, Anti-fungal Removable Gasket, Wider and Deeper Body Design, No. of Doo Double Door, Refrigerant: R-600A, Cooling Features: Direct Cool, Shelf Material: Toughened Wire Shelves, Shelf Material (Freezer): Toughened Wire Shelves",
    "image": "https://www.aysonline.pk/wp-content/uploads/2021/01/WhatsApp-Image-2021-01-20-at-3.57.31-PM.jpeg",
}, {
    "id": 24,
    "title": "Dawlance 9178 WB Long Freezer Avante+ Inverter - 353 Ltr/14 Cft - Glass Door",
    "Price": " 122,500.",
    "keyFeatures": "Warranty: 12 Years Compressor, Warranty: 1-Year Parts, Upto 35% Energy Saving, Works On as Low as 135V (No Need for Stabilizer), Modern Door Handle design, Anti-fungal Removable Gasket, Wider and Deeper Body Design, No. of Doo Double Door, Refrigerant: R-600A, Cooling Features: Direct Cool, Shelf Material: Toughened Wire Shelves, Shelf Material (Freezer): Toughened Wire Shelves",
    "image": "https://static-01.daraz.pk/p/b7882915e1dfdf63dfc597f42f8b6e54.jpg",
}, {
    "id": 25,
    "title": "Dawlance Refrigerator 9173WB GD Avante Pus Inverter 12CFT",
    "Price": " 111,600.",
    "keyFeatures": "Warranty: 12 Years Compressor, Warranty: 1-Year Parts, Upto 35% Energy Saving, Works On as Low as 135V (No Need for Stabilizer), Modern Door Handle design, Anti-fungal Removable Gasket, Wider and Deeper Body Design, No. of Doo Double Door, Refrigerant: R-600A, Cooling Features: Direct Cool, Shelf Material: Toughened Wire Shelves, Shelf Material (Freezer): Toughened Wire Shelves",
    "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcS1gqIxwylX_JMU_rt7h7_d4BrvZacKQ9pxvS6uWEU8ng&s",
}, {
    "id": 26,
    "title": "Haier HRF-538-IFPA Digital Inverter Refrigerator",
    "Price": " 133,000.",
    "keyFeatures": "Warranty: 10 Years, Refrigerator Capacity 501 to 600 liter, 18 Cubic Feet Capacity, Digital Inverter Compressor, Digital Control System, Humidity Control System, 2 Times Fresher, Refrigerator Features 2 in 1, 5 Conversion Modes, Glass Door, No. of Doors: Double Door, Color Green, Purple, Compressor Type Tropicalized Compressor, Technology Inverter",
    "image": "http://127.0.0.1:5501/Img/rh1.webp",
}, {
    "id": 27,
    "title": "HHaier HRF-538-IDRA Inverter Refrigerator",
    "Price": " 128,000.",
    "keyFeatures": "Warranty: 10 Years, Refrigerator Capacity 501 to 600 liter, 18 Cubic Feet Capacity, LVS 115V To 250V, 100 Hours Freezing, Cooling From 4 Sensors, 60% Saving, Refrigerator Features 2 in 1, 5 Conversion Modes, Glass Door, Touch Glass Door, No. of Doo Double Door, Color Green, Purple, Compressor Type Tropicalized Compressor, Technology Inverter",
    "image": "http://127.0.0.1:5501/Img/rh2.jpg",
}, {
    "id": 28,
    "title": "Haier HRF-438-IBSA Metal Door Inverter Refrigerator",
    "Price": " 98,000.",
    "keyFeatures": "Warranty: 10 Years, Refrigerator Capacity 401 to 500 liter, 2nd Generation FD Inverter, Faster Cooling and Freezing, A.SPE Sterilization Technology, Gross capacity Ltr: 438, Freezer Capacity Ltr: 120, Refrigerator Features 2 in 1, 5 Conversion Modes, Metallic, No. of Doo Double Door, Color Silver, Compressor Type Tropicalized Compressor, Technology Inverter",
    "image": "https://www.aysonline.pk/wp-content/uploads/2023/06/haier-inverter-metal-door-2-600x600.jpeg",
}, {
    "id": 29,
    "title": "Haier HRF-438 IDBA 16 Cubic Feet Inverter Refrigerator",
    "Price": " 115,000.",
    "keyFeatures": "Warranty: 10 Years, Warranty 10 Years Compressor, Refrigerator Capacity 401 to 500 liter, 2nd Generation FD Inverter, 105V~260V/50Hz, 16 Cubic Feet, Refrigerant: R-600a, Freezer Capacity Ltr: 120, Refrigerator Features 2 in 1, 5 Conversion Modes, Glass Door, No. of Doo Double Door, Refrigerator Cubic Feet 15 to 16 cubic feet, Compressor Type Tropicalized Compressor, Technology Inverter, Ice tray: 2",
    "image": "https://www.aysonline.pk/wp-content/uploads/2022/01/438IDBA-600x600.jpg.webp",
}, {
    "id": 30,
    "title": "Haier HRF-306 IDRA 11 Cubic Feet Inverter Refrigerator",
    "Price": " 94,000.",
    "keyFeatures": "Warranty: 10 Years, Warranty 10 Years Compressor, Refrigerator Capacity 301 to 400 liter, REF Shelf: Glass/3, Voltage: 105V~260V, 11 Cubic Feet, Refrigerant: R-600a, Freezer Capacity: 93, REF Capacity Ltr: 183, Refrigerator Features 2 in 1, 5 Conversion Modes, Glass Door, No. of Doo Double Door, REF Shelf: Glass/3, Compressor Type Tropicalized Compressor, Technology Inverter",
    "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRE0ufhOFLjTwUtxDLQ6AdAQcIQdn3t7425BOWn05M4cA&s",
}, {
    "id": 31,
    "title": "Dawlance WD-1051 Glass Door Water Dispenser (Silver + Black)",
    "Price": " 47,000.",
    "keyFeatures": "Warranty: 1 Years, 220-240V/ 400 watts, Process Capacity Cool: 1L/H, Process Capacity Hot: 5L/H, Storage Capacity Cool: 3.5L, Storage Capacity Hot: 1L, 3 Taps (Hot/Normal/Cold), Child Safety Lock, Colo Black or Silver (Subject to availability), Stainless steel tanks for Health & Hygiene",
    "image": "https://eezepc.com/wp-content/uploads/2022/03/Dawlance-WD-1051-GD-0.jpg",
}, {
    "id": 32,
    "title": "Dawlance Water Dispenser WD-1051",
    "Price": " 42,000.",
    "keyFeatures": "3 years compressor warranty, 17% bigger cold water tank, 3 taps; Normal, Hot, Cold, Premium Glass Door design, Stainless steel tanks for Health & Hygiene, Specially designed for Pakistani market, 40% bigger refrigerator portion, 60% bigger hot water tank, 20L Refrigerator Compartment",
    "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcREZCnnV80rZmVt5F13cEVJGr0uzZgOw4AF5LVEsdxsbA&s",
}, {
    "id": 33,
    "title": "Dawlance Water Dispenser WD-1051 GD",
    "Price": " 42,000.",
    "keyFeatures": "3 years compressor warranty, 1.6L Hot Water Tank, • 3.5L Cold Water Tank, 17% bigger cold water tank, 3 taps; Normal, Hot, Cold, Premium Glass Door design, Stainless steel tanks for Health & Hygiene, Specially designed for Pakistani market, 40% bigger refrigerator portion, 60% bigger hot water tank, 20L Refrigerator Compartment",
    "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTeYClUorOwMO4QujJ_OZKbMuIheCrpbOlUchnBWVlI-Q&s",
}, {
    "id": 34,
    "title": "Dawlance WD-1060 GREY",
    "Price": " 52,000.",
    "keyFeatures": "2 years compressor warranty, 3.5 L Cold Water Tank, 1.6 L Hot Water Tank, 20L Refrigerator Compartment, 3 taps; Normal, Hot, Cold, Premium Glass Door design, Stainless steel tanks for Health & Hygiene, Specially designed for Pakistani market, 17% bigger cold water tank, 60% bigger hot water tank, 40% bigger refrigerator portion",
    "image": "https://leyjao.pk/images/thumbnails/550/450/detailed/321/1060wo.jpg",
}, {
    "id": 35,
    "title": "Dawlance Water Dispenser WD 1060 White Without Refrigerator",
    "Price": " 35,000.",
    "keyFeatures": "2 years compressor warranty, Cooling Capacity: 2, Cold Water Tank Capacity: 3, Hot Water Capacity: 4, Hot Water Tank Capacity: 1, Premium Glass Door design, Stainless steel tanks for Health & Hygiene, Specially designed for Pakistani market, 17% bigger cold water tank, 60% bigger hot water tank, Taps: Hot & Cold, Without Refrigerator",
    "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQLNbml2HHq0O3nWtpFFDCRdzBcSE0ViHbBVBi6wQaDFw&s",
}, {
    "id": 36,
    "title": "Haier HWD 3409G Dispenser",
    "Price": " 41,500.",
    "keyFeatures": "3 years compressor warranty, Cooling Capacity: 2, Cold Water Capacity(L/H): 3.5, Hot Water Capacity(L/H): 1.5, Cold Water Power consumption(W/A): 120, Hot Water Power consumption(W/A): 500, Color: Red, Security Button: Yes, Cabinet Capacity(L): 14, Refrigerator Cabinet: Yes, Storage Cabinet: Yes, Taps: Hot & Cold, Double Door: Yes",
    "image": "https://ezmakaan.com/wp-content/uploads/2019/03/dd2.jpg",
}, {
    "id": 37,
    "title": "Haier Water Dispenser HWD-336Y With Refrigerator Glass Door – 2 Tap – Golden",
    "Price": " 39,500.",
    "keyFeatures": "3 years compressor warranty, Cooling Capacity: 2, Brand Warranty, Two Faucet & Two Water Temperatures, Elegant Design, Indicator Light, Color: Golden, Child Safety Lock, With 6 Rings Copper, 20 L Refriegerator Capacity., Voltage: 220-240 V, Taps: Hot & Cold, Double Door: Yes",
    "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQqfzHQu-XEnh2y-IcC1hOonYG7eIsFZz80xV2xhU9R3A&s",
}, {
    "id": 38,
    "title": "Haier HWD-3209G Water Dispenser",
    "Price": " 39,000.",
    "keyFeatures": "3 years compressor warranty, Cooling System Compressor, Net Refrigerator Capacity (L) 14, Housing Color / Material Silver / Red, Approvals CE/GS, Power Consump. Cold-Hot (W) 80-500, Color Silver / Red, Child Safety Lock, Power Consump. Cold-Hot (W) 80-500, Water Capacity Cold-Hot (L) 2.8-5, Cold Water Temp. (C) 6~10, Hot Water Temp. (C) 88~95, Taps: Hot & Cold, Double Door: Yes",
    "image": "https://ezmakaan.com/wp-content/uploads/2019/03/d1.jpg",
}, {
    "id": 39,
    "title": "Haier -HWD-336G Water Dispenser 4 L",
    "Price": " 38,000.",
    "keyFeatures": "3 years compressor warranty, Cooling System Compressor, The volume of the Cold Water Tank: 4 L., The volume of Hot Water Tank: 1 L., Hot and Cool water button on back, Child Safety Lock for Hot Water, Fast cooling performance with Danfu compressor, Child Safety Lock, High power stainless steel hot water tank, Cooling Method: Compressor, Stretched cold water tank, Stretched cold water tank, Taps: Hot & Cold, Double Door: Yes",
    "image": "https://lahorelectronics.com/wp-content/uploads/2021/08/hwd-336r.jpg",
}, {
    "id": 40,
    "title": "Haier New Water Dispenser HWD-206R White",
    "Price": " 35,000.",
    "keyFeatures": "3 years compressor warranty, Cooling System Compressor, 3 L S.S Cold Tank., Danfu Brand Compressor, Elegant Design, 12 L Refrigerator Capacity., Fast cooling performance with Danfu compressor, Child Safety Lock, Color: White, Cooling Method: Compressor, Color: White, Stainless Steel Water Tank, Taps: Hot & Cold, Double Door: Yes",
    "image": "https://lahorelectronics.com/wp-content/uploads/2022/05/hwd-206r-1.jpg",
}, {
    "id": 41,
    "title": "Dawlance DW 1775 PL 17KG Automatic Washing Machine Top Load",
    "Price": " 139,500.",
    "keyFeatures": "Jumbo Capacity 17KG, Warranty: 1 Years parts, Warranty: 3 Years PCB, Warranty: 10 Years Motor, Triple Waterfall Technology, Extreme Plus Air Dryer, Pro Fabric Drum, Glass Lid, Operators at a voltage as low as 150 volts, Extended capacity for a Normal Sized Household, E-Care Series-Saves up to 40% Energy",
    "image": "http://127.0.0.1:5501/Img/wmd1.png",
}, {
    "id": 42,
    "title": "Dawlance DWT 1775 PL Automatic Washing Machine",
    "Price": " 119,000.",
    "keyFeatures": "17Kg Capacity, Warranty: 1 Years parts, Warranty: 3 Years PCB, Warranty: 10 Years Motor, 40% Energy Saving, Touch Panel, Low Voltage Startup 150V, Glass Lid, Triple Water Fall Technology, 10 Washing Functions, Pro Fabric Drum",
    "image": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQS5NU-L6LwB9_-54-oY4vWgfPSPfiD-hmdSuzdQjDEFQ&s",
}, {
    "id": 43,
    "title": "Dawlance DWT 1470 PL Automatic Washing Machine",
    "Price": " 73,000.",
    "keyFeatures": "14Kg Capacity, Warranty: 1 Years parts, Warranty: 3 Years PCB, Warranty: 10 Years Motor, 40% Energy Saving, Touch Panel, Low Voltage Startup 150V, Glass Lid, Triple Water Fall Technology, 10 Washing Functions, Pro Fabric Drum",
    "image": "https://electronicspakistan.com/wp-content/uploads/2022/12/b-23.jpg",
}, {
    "id": 44,
    "title": "Dawlance DWF-8120 GR Inverter Automatic Washing Machine",
    "Price": " 228,000.",
    "keyFeatures": "Warranty: 1 Years parts, Warranty: 3 Years PCB, Warranty: 10 Years Motor, 8 Kg Wash Capacity, Inverter Technology, Hygiene Wash kills up to 99.9 % of Bacteria, Embroidery Care Program, Special Algorithms for Wool, Noise level of 48 dB",
    "image": "https://www.aysonline.pk/wp-content/uploads/2021/03/dawlance-front-load-fully-automatic-washing-machine-8kg-_dwf-8400s-inv__1.jpg.webp",
}, {
    "id": 45,
    "title": "DAWLANCE DWF7200X Inverter Front Load Washing Machine (7KG)",
    "Price": " 165,000.",
    "keyFeatures": "Warranty: 1 Years parts, Warranty: 3 Years PCB, Warranty: 10 Years Motor, 7 Kg Wash Capacity, Remote Connectivity through HomeWhiz Bluetooth, Hygiene Wash kills up to 99.9 % of Bacteria, Special Algorithms for Wools, Stain Buster Technology, Energy Rating of A+++(-10%), Steam Care Technology",
    "image": "https://i0.wp.com/www.brandsmerkez.com/wp-content/uploads/2021/09/Dw7200.jpg?fit=680%2C850&ssl=1",
}, {
    "id": 46,
    "title": "Haier HW100-BP14929S3 Automatic Front Load Washing Machine",
    "Price": " 175,000.",
    "keyFeatures": "Warranty: 1 Years parts,Warranty: 3 Years PCB,Warranty: 10 Years Motor,10 Kg Wash Capacity,Remote Connectivity through HomeWhiz Bluetooth,Hygiene Wash kills up to 99.9 % of Bacteria,Super Inverter,Super XL Drum,Highest Spin Speed: 1400,Auto Lock Door,Steam,Pillow Drum",
    "image": "http://127.0.0.1:5501/Img/wmh1.jpeg",
}, {
    "id": 47,
    "title": "Haier HS 120-B1978 S9 Top Load Washing Machine",
    "Price": " 156,000.",
    "keyFeatures": "Warranty: 10 Years Motor, Width x Depth x Height (mm): 580x550x1010, Net Weight / Gross Weight (kg):, 12 Kg Wash Capacity, Net Weight / Gross Weight (kg):, Drying Capacity (kg):, Child lock, No Heating Without Water, Spin Speed: 1400, Highest Spin Speed: 1400, Auto Lock Door, Steam, Spin Speed (rpm): 1400",
    "image": "http://127.0.0.1:5501/Img/wmh2.webp",
}, {
    "id": 48,
    "title": "Haier HS 150-B1978 S9 Top Load Washing Machine",
    "Price": " 162,000.",
    "keyFeatures": "Warranty: 10 Years Motor, Width x Depth x Height (mm): 610x575x1020, Net Weight / Gross Weight (kg):, 15 Kg Wash Capacity, Net Weight / Gross Weight (kg):, Drying Capacity (kg):, Child lock, Display: Touch, No Heating Without Water, Spin Speed: 1400, Highest Spin Speed: 1400, Auto Lock Door, Steam, Spin Speed (rpm): 1400",
    "image": "http://127.0.0.1:5501/Img/wmh3.jpg",
}, {
    "id": 49,
    "title": "HAIER 12KG AUTOMATIC TOP LOAD WASHING MACHINE Model HWM 120-1789 BG",
    "Price": " 98,000.",
    "keyFeatures": "Warranty: 10 Years Motor, Automatic washing machine for easy use, Net Weight / Gross Weight (kg):, Additional Features: 3D Wash, Pillow Drum, Auto Restart, 12 Kg Wash Capacity, Spin Capacity: 12 kg, Drying Capacity (kg):, Child lock, Display: Touch, No Heating Without Water, Spin Speed (RPM): 1300, Highest Spin Speed: 1300, Auto Lock Door, Steam, Color: Grey",
    "image": "http://127.0.0.1:5501/Img/wmh4.webp",
}, {
    "id": 50,
    "title": "Haier HWM 90-1789 Top Load Washing Machine",
    "Price": " 162,000.",
    "keyFeatures": "Warranty: 10 Years Motor, Automatic washing machine for easy use, Net Weight / Gross Weight (kg):, Additional Features: 3D Wash, Pillow Drum, Auto Restart, 12 Kg Wash Capacity, Spin Capacity: 9 kg, Drying Capacity (kg):, Child lock, Display: Touch, No Heating Without Water, Spin Speed (RPM): 1100, Highest Spin Speed: 1100, Auto Lock Door, Steam, Color: Grey",
    "image": "http://127.0.0.1:5501/Img/wmh5.jpg",
}, {
    "id": 51,
    "title": "Dawlance Blender DWTB-620",
    "Price": " 162,000.",
    "keyFeatures": "1-year official brand warranty, 500W Motor – blends the toughest of the ingredients homogeneously, Dry Mill attachment, Ice Crushing, Safety Lock, Strong Blades – for hard objects, Inbox Body, Glass Jug, Capacity (Lt) 1.7 L, Power (W) 500 W, Bowl Capacity (Lt) 1.7 L, Speed level 2, Depth 1 cm, Height 1 cm, weight 1 KG",
    "image": "http://127.0.0.1:5501/Img/bd1.png",
}, {
    "id": 52,
    "title": "Dawlance Blender DWTB 510 W",
    "Price": " 13,000.",
    "keyFeatures": "1-year official brand warranty, 400W Motor blends the toughest of the ingredients homogeneously, Dry Mill attachment, Ice Crushing, Safety Lock, Strong Blades – for hard objects, Inbox Body, Glass Jug, Capacity (Lt) 1.5 L, Bowl Capacity (Lt) 1.5 L, Speed level 2, Depth 1 cm, Height 1 cm, weight 1 KG",
    "image": "http://127.0.0.1:5501/Img/bd2.jpg",
}, {
    "id": 53,
    "title": "Dawlance BLENDER DWTB-590 WHITE",
    "Price": " 11,750.",
    "keyFeatures": "1-year official brand warranty, 500W Motor blends the toughest of the ingredients homogeneously, Dry Mill attachment, Ice Crushing, Safety Lock, Strong Blades – for hard objects, Inbox Body, Glass Jug, Capacity (Lt) 1.7 L, Bowl Capacity (Lt) 1.7 L, Speed level 2, Anti-Slip Rubber Pad: Yes, Dishwasher-Safe Parts: Yes",
    "image": "http://127.0.0.1:5501/Img/bd3.webp",
}, {
    "id": 54,
    "title": "DAWLANCE JUICER DWHJ 4002B",
    "Price": " 25,300.",
    "keyFeatures": "1-year official brand warranty, 500W Motor blends the toughest of the ingredients homogeneously, Dry Mill attachment, Ice Crushing, Safety Lock, Strong Blades – for hard objects, Inbox Body, Glass Jug, Feeding Tube Size (mm) 65, Power 400(W), Speed level 2, Detachable Pulp Container: Yes, Filter Cleaning Brush: Yes",
    "image": "http://127.0.0.1:5501/Img/bd4.jpg",
}, {
    "id": 55,
    "title": "DAWLANCE Juicer DWHJ 8002I",
    "Price": " 20,000.",
    "keyFeatures": "1-year official brand warranty, 500W Motor blends the toughest of the ingredients homogeneously, Dry Mill attachment, Ice Crushing, Safety Lock, Voltage: 220-240V / 50-60Hz, Inbox Body, Glass Jug, Precise & Durable Full Metal Spinner, Power 500(W), Premium Black Color, Detachable Pulp Container: Yes, Filter Cleaning Brush: Yes, European Quality Product",
    "image": "http://127.0.0.1:5501/Img/bd5.jpg",
}, {
    "id": 56,
    "title": "Haier Blender HBL1056GC-CB",
    "Price": " 25,000.",
    "keyFeatures": "1-year official brand warranty, Capacity: 1.5L, 220-240V ~50-60Hz, 500W, Plastic Body with stainless steel decoration, Safety Lock, Stainless steel blades, With grinder jug, Glass Jug, Can blend different kinds of fruit juice, 8 speeds control, Anti-slip feet design, Detachable Pulp Container: Yes, Filter Cleaning Brush: Yes, European Quality Product",
    "image": "http://127.0.0.1:5501/Img/bh1.webp",
}, {
    "id": 57,
    "title": "Haier I-Master Series 5 Glass Jug Blender",
    "Price": " 35,000.",
    "keyFeatures": "2-year official brand warranty, 0.6L bottle for smoothies on the go, 6 Laser-sharp blades, 1200W motor, Safety Lock, Stainless steel blades, With grinder jug, Glass Jug, 1.7L Glass Jug. Easily cleaned with no impact on taste, 8 speeds control, Anti-slip feet design, Detachable Pulp Container: Yes, Filter Cleaning Brush: Yes, European Quality Product",
    "image": "http://127.0.0.1:5501/Img/bh2.webp",
}, {
    "id": 58,
    "title": "Haier Blender GRINDER 3 IN 1 Model AG-6032",
    "Price": " 12,000.",
    "keyFeatures": "2-year official brand warranty, Capacity: 1.5L, Product Type: 3-in-1 Blender and Grinder, Speeds: 3 speed and pulse control, Safety Lock, Safety: Safety switch lock clamps, Jug Material: Stainless steel, Glass Jug, Weight: 2.50 kg, Dimensions: 19.30 × 31.50 × 28.80 cm, Anti-slip feet design, Safety: It features safety switch lock clamps., Filter Cleaning Brush: Yes",
    "image": "http://127.0.0.1:5501/Img/bh3.webp",
}, {
    "id": 59,
    "title": "Haier Juicer Blender Model HBL-1009",
    "Price": " 30,000.",
    "keyFeatures": "1-year official brand warranty, 500W Motor blends the toughest of the ingredients homogeneously, Dry Mill attachment, Ice Crushing, Safety Lock, Strong Blades – for hard objects, Inbox Body, Glass Jug, Feeding Tube Size (mm) 65, Power 400(W), Speed level 2, Detachable Pulp Container: Yes, Filter Cleaning Brush: Yes",
    "image": "http://127.0.0.1:5501/Img/bh4.webp",
}, {
    "id": 60,
    "title": "Haier Blender Haier HJE-1024L/1024B",
    "Price": " 25,000.",
    "keyFeatures": "1-year official brand warranty, 500W Motor blends the toughest of the ingredients homogeneously, Dry Mill attachment, Ice Crushing, Safety Lock, Strong Blades – for hard objects, Inbox Body, Glass Jug, Feeding Tube Size (mm) 65, Power 400(W), Speed level 2, Detachable Pulp Container: Yes, Filter Cleaning Brush: Yes",
    "image": "http://127.0.0.1:5501/Img/bh3.webp",
}, {
    "id": 61,
    "title": "Dawlance Electric Kettle DWEK 7210",
    "Price": " 12,000.",
    "keyFeatures": "1-year official brand warranty, Capacity 1.7L, Large capacity with 2200W power, Water gauge on both sides, Automatic lid opening, Six control, Switch with indicate light, Fast and efficient boiling of water, Automatic shut-off function for safety, Concealed heating element for durability and safety, Large capacity for convenience, Easy to use and clean, Stylish design, Color Red",
    "image": "http://127.0.0.1:5501/Img/de1.webp",
}, {
    "id": 62,
    "title": "Dawlance Kettle DWEK-7200",
    "Price": " 8,000.",
    "keyFeatures": "1-year official brand warranty, Capacity 1L, Large capacity with 1200W power, Automatic lid opening, Six control, Switch with indicate light, Fast and efficient boiling of water, Automatic shut-off function for safety, Concealed heating element for durability and safety, Large capacity for convenience, Easy to use and clean, Stylish design, Color White",
    "image": "http://127.0.0.1:5501/Img/de2.webp",
}, {
    "id": 63,
    "title": "Dawlance Kettle DWEK-7100",
    "Price": " 7,800.",
    "keyFeatures": "1-year official brand warranty, Capacity 1L, Large capacity with 1200W power, Automatic lid opening, Six control, Switch with indicate light, Fast and efficient boiling of water, Automatic shut-off function for safety, Concealed heating element for durability and safety, Large capacity for convenience, Easy to use and clean, Stylish design, Color Black",
    "image": "http://127.0.0.1:5501/Img/de3.webp",
}, {
    "id": 64,
    "title": "Dawlance Kettle DWEK-8212",
    "Price": " 8,000.",
    "keyFeatures": "1-year official brand warranty, Capacity 1.7L, Large capacity with 2200W power, Automatic lid opening, Six control, Switch with indicate light, Fast and efficient boiling of water, Automatic shut-off function for safety, Concealed heating element for durability and safety, Large capacity for convenience, Easy to use and clean, Stylish design, Color Black",
    "image": "http://127.0.0.1:5501/Img/de4.jpg",
}, {
    "id": 65,
    "title": "Dawlance Kettle DWEK 7220 MG",
    "Price": " 8,000.",
    "keyFeatures": "1-year official brand warranty, Capacity 1.7L, Large capacity with 2200W power, Automatic lid opening, Six control, Switch with indicate light, Fast and efficient boiling of water, Automatic shut-off function for safety, Concealed heating element for durability and safety, Large capacity for convenience, Easy to use and clean, Stylish design, Color Silver",
    "image": "http://127.0.0.1:5501/Img/de5.png",
}, {
    "id": 66,
    "title": "Haier Electric Kettle HKT-4401 (Silver and Red)",
    "Price": " 9,500.",
    "keyFeatures": "1-year official brand warranty, Capacity 1.5L, Large capacity with 2200W power, Automatic lid opening, Six control, Switch with indicate light, Fast and efficient boiling of water, Automatic shut-off function for safety, Concealed heating element for durability and safety, Large capacity for convenience, Easy to use and clean, Stylish design, Color Silver & Red",
    "image": "http://127.0.0.1:5501/Img/he1.jpg",
}, {
    "id": 67,
    "title": "Haier Electric Kettle HKT-1797 (White and Black)",
    "Price": " 7,500.",
    "keyFeatures": "1-year official brand warranty, Capacity 1.7L, Large capacity with 2200W power, Automatic lid opening, Six control, Switch with indicate light, Fast and efficient boiling of water, Automatic shut-off function for safety, Concealed heating element for durability and safety, Large capacity for convenience, Easy to use and clean, Stylish design, Color Silver & Black",
    "image": "http://127.0.0.1:5501/Img/he2.jpeg",
}, {
    "id": 68,
    "title": "Haier Electric Kettle HKT-1797v (White and Black)",
    "Price": " 8,000.",
    "keyFeatures": "1-year official brand warranty, Capacity 1.7L, Large capacity with 2200W power, Automatic lid opening, Six control, Switch with indicate light, Fast and efficient boiling of water, Automatic shut-off function for safety, Concealed heating element for durability and safety, Large capacity for convenience, Easy to use and clean, Stylish design, Color Silver & Black",
    "image": "http://127.0.0.1:5501/Img/he3.jpg",
}, {
    "id": 69,
    "title": "Haier Electric Kettle HKT-1708 (Silver)",
    "Price": " 5,000.",
    "keyFeatures": "1-year official brand warranty, Capacity 1.7L, Large capacity with 1850W power, Automatic lid opening, Six control, Switch with indicate light, Fast and efficient boiling of water, Automatic shut-off function for safety, Concealed heating element for durability and safety, Large capacity for convenience, Easy to use and clean, Stylish design, Color Silver",
    "image": "http://127.0.0.1:5501/Img/he4.jpeg",
}, {
    "id": 70,
    "title": "Haier Electric Kettle HKT-4401S (Silver)",
    "Price": " 7,000.",
    "keyFeatures": "1-year official brand warranty, Capacity 1.7L, Large capacity with 2200W power, Automatic lid opening, Six control, Switch with indicate light, Fast and efficient boiling of water, Automatic shut-off function for safety, Concealed heating element for durability and safety, Large capacity for convenience, Easy to use and clean, Stylish design, Color Silver",
    "image": "http://127.0.0.1:5501/Img/he5.jpg",
}, {
    "id": 71,
    "title": "Dawlance Cooking Range 98DFF (Turbo Fan)",
    "Price": " 310,000.",
    "keyFeatures": "1-year official brand warranty, Thermostat to regulate the oven temperature, Italian spare parts, Made in Turkey, Self-cleaning system, Full safety system, Self-cleaning system, Turbo Fan, size : 90 cm, Closed door grill, Self-ignition, Color Silver",
    "image": "http://127.0.0.1:5501/Img/DC1.webp",
}, {
    "id": 72,
    "title": "Dawlance Cooking Range 98DFF (Without Fan)",
    "Price": " 175,000.",
    "keyFeatures": "1-year official brand warranty, Thermostat to regulate the oven temperature, Italian spare parts, Made in Turkey, Self-cleaning system, Full safety system, Self-cleaning system, Without Fan, size : 90 cm, Closed door grill, Self-ignition, Color Silver",
    "image": "http://127.0.0.1:5501/Img/dc2.jpg",
}, {
    "id": 73,
    "title": "Dawlance Cooking Appliances DBE 208110 S A",
    "Price": " 94,000.",
    "keyFeatures": "1-year official brand warranty, Thermostat to regulate the oven temperature, Mechanical Minute Minder – with Cut-off, Electric Oven Type, Double Glass Door, Self-cleaning system, Power consumption 143 W, Dimension 59.4 x 56 x 59.5 cm, Closed door grill, Control Panel Type B14 Design, Large Cavity, Color Black",
    "image": "http://127.0.0.1:5501/Img/dc3.webp",
}, {
    "id": 74,
    "title": "Dawlance Cooking Appliances DBM 208110 M A",
    "Price": " 94,000.",
    "keyFeatures": "1-year official brand warranty, Thermostat to regulate the oven temperature, Mechanical Minute Minder – with Cut-off, Electric Oven Type, Triple Glass Door, Voltage 220-240, Power consumption 143 W, Dimension 59.4 x 56 x 59.5 cm, Closed door grill, Control Panel Type B14 Design, Large Cavity, Color Silver",
    "image": "http://127.0.0.1:5501/Img/dc4.webp",
}, {
    "id": 75,
    "title": "Dawlance Cooking Appliances DBM 208110 B A",
    "Price": " 94,000.",
    "keyFeatures": "1-year official brand warranty, Thermostat to regulate the oven temperature, Mechanical Minute Minder – with Cut-off, Electric Oven Type, Triple Glass Door, Voltage 220-240, Power consumption 143 W, Dimension 59.4 x 56 x 59.5 cm, Closed door grill, Control Panel Type B14 Design, Large Cavity, Color Inox",
    "image": "http://127.0.0.1:5501/Img/dc5.webp",
}, {
    "id": 76,
    "title": "Haier Built-In Baking Oven 56 Liter HWO60S4MGX1 Dual Fuel (Electric & Gas)",
    "Price": " 99,500.",
    "keyFeatures": "1-year official brand warranty, Thermostat to regulate the oven temperature, Mechanical Minute Minder – with Cut-off, Electric Oven Type, Double Glass Door, Voltage 220-240, Power consumption 143 W, Timer 120 mins, Closed door grill, Outer Dimensions 595*595*558, Large Cavity, Color Silver",
    "image": "http://127.0.0.1:5501/Img/hc1.webp",
}, {
    "id": 77,
    "title": "Haier Oven HW O60S10EB1 Baking| Convection| 56 Liters (Electric Oven| Black)",
    "Price": " 107,500.",
    "keyFeatures": "1-year official brand warranty, Thermostat to regulate the oven temperature, Mechanical Minute Minder – with Cut-off, Electric Oven Type, Double Glass Door, Voltage 220-240, Power consumption 143 W, Timer 120 mins, Closed door grill, Outer Dimensions 595*595*558, Large Cavity, Color Silver, No of function 10",
    "image": "http://127.0.0.1:5501/Img/hc2.webp",
}, {
    "id": 78,
    "title": "Haier HWO60S4MGB1 Dual Built-In-Oven",
    "Price": " 120,000.",
    "keyFeatures": "1-year official brand warranty, Thermostat to regulate the oven temperature, Mechanical Minute Minder – with Cut-off, Electric Oven Type, Double Glass Door, Voltage 220-240, Power consumption 143 W, Timer 120 mins, Closed door grill, Double layer of glass oven door, Large Cavity, Color Black, Dual fuel of gas and electric with 8 Functions",
    "image": "http://127.0.0.1:5501/Img/hc3.webp",
}, {
    "id": 79,
    "title": "Haier HWO 60S7EX1 Dual Built-In-Oven",
    "Price": " 118,000.",
    "keyFeatures": "1-year official brand warranty, Thermostat to regulate the oven temperature, Mechanical Minute Minder – with Cut-off, Electric Oven Type, Double Glass Door, Voltage 220-240, Power consumption 143 W, Timer 120 mins, Closed door grill, Double layer of glass oven door, Large Cavity, Color Silver, Dual fuel of gas and electric with 7 Functions",
    "image": "http://127.0.0.1:5501/Img/hc4.webp",
}, {
    "id": 80,
    "title": "Haier Builtin Oven HWO 60S7EX1",
    "Price": " 110,000.",
    "keyFeatures": "1-year official brand warranty, Thermostat to regulate the oven temperature, Mechanical Minute Minder – with Cut-off, Electric Oven Type, Double Glass Door, Voltage 220-240, Power consumption 143 W, Time 120 mins, Closed door grill, Double layer of glass oven door, Large Cavity, Color Silver, Dual fuel of gas and electric with 7 Functions",
    "image": "http://127.0.0.1:5501/Img/hc5.webp",
}, {
    "id": 81,
    "title": "Dawlance DDW-1451 Inverter Dishwasher",
    "Price": " 164,000.",
    "keyFeatures": "1-year official brand warranty, Easy User Interface with operation with a single touch, Hygiene Wash at 70º, Inverter Motor, Aqua Intense Techonology, Saves Water Efficiently, End of Programme Indicator: Yes, Rinse Aid, Active Fan Drying Technology, Number of Programs: 5, Auto Clean Program, Color Silver, Water Consumption 9.5L, Capacity 14 Place",
    "image": "http://127.0.0.1:5501/Img/Dw1.jpg",
}, {
    "id": 82,
    "title": "Dawlance DDW-1480I INV Free standing Dishwasher",
    "Price": " 200,000.",
    "keyFeatures": "1-year official brand warranty, Easy User Interface with operation with a single touch, Hygiene Wash at 70º, Inverter Motor, Aqua Intense Technology, Saves Water Efficiently, End of Programme Indicator: Yes, Rinse Aid, Saves Water Efficiently, 85000 Liters of Water Saving, Auto Clean Program, Hygienic Wash, Color Silver, Water Consumption 9.5L, Capacity 14 Place",
    "image": "http://127.0.0.1:5501/Img/dw2.jpg",
}, {
    "id": 83,
    "title": "DAWLANCE Dishwasher DW 1350",
    "Price": " 150,000.",
    "keyFeatures": "1-year official brand warranty, Easy User Interface with operation with a single touch, Hygiene Wash at 70º, Inverter Motor, Aqua Intense Technology, Saves Water Efficiently, End of Programme Indicator: Yes, Power Input, Frequency 220-240 V, 50 Hz., Saves Water Efficiently, Power Consumption 1800-2100 W, Auto Clean Program, Hygienic Wash, Color Silver, Water Consumption 11.5L, Capacity 13 Place",
    "image": "http://127.0.0.1:5501/Img/dw3.jpg",
}, {
    "id": 84,
    "title": "Dawlance DDW-1485G INV 8 Program 14Place CapacityInverter Dish Washer",
    "Price": " 135,000.",
    "keyFeatures": "1-year official brand warranty, Easy User Interface with operation with a single touch, Hygiene Wash at 70º, Inverter Motor, Aqua Intense Technology, Saves Water Efficiently, End of Programme Indicator: Yes, Power Input, Frequency: 220-240 V, 50 Hz., Saves Water Efficiently, Power Consumption: 1800-2100 W, Auto Clean Program, Hygienic Wash, Color Black, Water Consumption 9.5L, Capacity 14 Place",
    "image": "http://127.0.0.1:5501/Img/dw4.jpeg",
}, {
    "id": 85,
    "title": "DAWLANCE 60X60 CM COUNTER TOP DISHWASHER Model DWW 868 CTB",
    "Price": " 100,000.",
    "keyFeatures": "1-year official brand warranty, Easy User Interface with operation with a single touch, Hygiene Wash at 70º, Inverter Motor, Aqua Intense Technology, Saves Water Efficiently, End of Programme Indicator: Yes, Power Input, Frequency: 220-240 V, 50 Hz., Saves Water Efficiently, Power Consumption: 1800-2100 W, Auto Clean Program, Hygienic Wash, Color Black, Water Consumption 8L, Capacity 8 Place",
    "image": "http://127.0.0.1:5501/Img/dw5.webp",
}, {
    "id": 86,
    "title": "Haier Dishwasher DW14-KFFWWPK / White",
    "Price": " 150,000.",
    "keyFeatures": "1-year official brand warranty, Easy User Interface with operation with a single touch, Hygiene Wash at 70º, Inverter Motor, Aqua Intense Technology, Saves Water Efficiently, White Door Protection, 4 Cleaning Temperatures, Saves Water Efficiently, Speedmatic, Auto Clean Program, Hygienic Wash, Color white, Water Consumption 9.5L, Capacity 14 Place",
    "image": "http://127.0.0.1:5501/Img/dh1.webp",
}, {
    "id": 87,
    "title": "Haier 15 Place Setting 6 Program Freestanding Dishwasher - Satina (HDW15F2S1)",
    "Price": " 250,000.",
    "keyFeatures": "1-year official brand warranty, Easy User Interface with operation with a single touch, Hygiene Wash at 70º, Inverter Motor, Aqua Intense Technology, 15 Place Setting Capacity, White Door Protection, 246 kWh/year Energy Consumption; 4 Energy Star Rating, Saves Water Efficiently, Door Features: Pull Down Door Opening with a Recessed Handle, Auto Clean Program, Hygienic Wash, Color white, Water Consumption 12.2L, 246 kWh/year Energy Consumption; 4 Energy Star Rating, 15 Place Setting Capacity",
    "image": "http://127.0.0.1:5501/Img/dh2.avif",
}, {
    "id": 88,
    "title": "Haier Freestanding Dishwasher HDW13V1W1",
    "Price": " 180,000.",
    "keyFeatures": "1-year official brand warranty, Easy User Interface with operation with a single touch, Hygiene Wash at 70º, Inverter Motor, Aqua Intense Technology, 13 Place Setting Capacity, White Door Protection, Dishwasher type Freestanding, Saves Water Efficiently, Door Features: Pull Down Door Opening with a Recessed Handle, Auto Clean Program, Accessories included 1 x 1500mm Cold water inlet Hose, 1 x 2060mm Drain Outlet Hose., Color white, Water Consumption 12.2L, Auto Power off",
    "image": "http://127.0.0.1:5501/Img/dh3.webp",
}, {
    "id": 89,
    "title": "Haier Freestanding Dishwasher with Steam Satina HDW15F3S1",
    "Price": " 280,000.",
    "keyFeatures": "1-year official brand warranty, Easy User Interface with operation with a single touch, Hygiene Wash at 70º, Inverter Motor, Aqua Intense Technology, 15 Place Setting Capacity, White Door Protection, 246 kWh/year Energy Consumption; 4 Energy Star Rating, Saves Water Efficiently, Door Features: Pull Down Door Opening with a Recessed Handle, Auto Clean Program, Hygienic Wash, Color white, Water Consumption 12.2L, 246 kWh/year Energy Consumption; 4 Energy Star Rating, 15 Place Setting Capacity",
    "image": "http://127.0.0.1:5501/Img/dh4.jpeg",
}, {
    "id": 90,
    "title": "Haier 15-Place Setting Freestanding Dishwasher (Black)",
    "Price": " 200,000.",
    "keyFeatures": "1-year official brand warranty, Load capacity (place settings) 15, Dishwasher water consumption (litres) 11.1, Cutlery drawer Yes, Energy star rating 5.5, Water star rating 4.5, White Door Protection, Smart features Yes, Product Height (mm)895, Maximum height (mm)895, Product Depth (mm)599, Product Depth (mm)599, Color Black, Product Depth (mm)599, Packaged Width (mm)700, Packaged Depth (mm)660",
    "image": "http://127.0.0.1:5501/Img/dh5.webp",
}, {
    "id": 91,
    "title": "Dawlance Air Fryer Model no 3013",
    "Price": " 22,000.",
    "keyFeatures": "1-year official brand warranty, TPot capacity 3 L, Material of main body Non-stick coating, Temperature control Yes, Weight 1kg, Power 1300 W, Timer Yes, size : 90 cm, Power Consumption, Air fry, roast, bake, grill, and reheat foods, Color Black",
    "image": "http://127.0.0.1:5501/Img/DF1.webp",
}, {
    "id": 92,
    "title": "SILVERCREST SC-800 – Air Fryer, 8L Multifonction Air Fryer",
    "Price": " 15,000.",
    "keyFeatures": "Checking Warranty Only, 8L Air Fryer, 220V, 50Hz, 3800W, EU plug, Non-stick detachable food basket, available dishwasher cleaning, and easy to clean, High-speed air circulation technology frying delicious food, not greasy, Tastiest food and snacks without oil, Up to 80% less fat, Adjust the time and temp. control, Effect of high power performance for fast cooking, Power Consumption, Air fry, roast, bake, grill, and reheat foods, Color Black",
    "image": "http://127.0.0.1:5501/Img/df2.jpg",
}, {
    "id": 93,
    "title": "Silver Crest 10L Large Capacity Air fryer Grill- Black",
    "Price": " 13,000.",
    "keyFeatures": "Checking Warranty Only, 10L Air Fryer, 220V, 50Hz, 3800W, EU plug, Non-stick detachable food basket, available dishwasher cleaning, and easy to clean, High-speed air circulation technology frying delicious food, not greasy, Tastiest food and snacks without oil, Up to 80% less fat, Adjust the time and temp. control, Effect of high power performance for fast cooking, Power Consumption, Air fry, roast, bake, grill, and reheat foods, Color Black",
    "image": "http://127.0.0.1:5501/Img/df3.jpg",
}, {
    "id": 94,
    "title": "Silver Crest S-18 Extra Large Air Fryer",
    "Price": " 14,000.",
    "keyFeatures": "Checking Warranty Only, 6L Air Fryer, 220V, 50Hz, 3800W, EU plug, Non-stick detachable food basket, available dishwasher cleaning, and easy to clean, High-speed air circulation technology frying delicious food, not greasy, Tastiest food and snacks without oil, Up to 80% less fat, Adjust the time and temp. control, Effect of high power performance for fast cooking, Power Consumption, Air fry, roast, bake, grill, and reheat foods, Color Black",
    "image": "http://127.0.0.1:5501/Img/df4.jpg",
}, {
    "id": 95,
    "title": "Silver Crest Digital LCD 8L Multifunctional All in 1 Home Fryer",
    "Price": " 15,000.",
    "keyFeatures": "Checking Warranty Only, 8L Air Fryer, 220V, 50Hz, 3800W, EU plug, Non-stick detachable food basket, available dishwasher cleaning, and easy to clean, High-speed air circulation technology frying delicious food, not greasy, Tastiest food and snacks without oil, Up to 80% less fat, Adjust the time and temp. control, Effect of high power performance for fast cooking, Power Consumption, Air fry, roast, bake, grill, and reheat foods, Color Random",
    "image": "http://127.0.0.1:5501/Img/DF5.jpg",
}, {
    "id": 96,
    "title": "Haier Air Fryer 4Liter HAF35B /Black",
    "Price": " 26,000.",
    "keyFeatures": "1 Years Warranty Only, 4L Air Fryer, 220V, 50Hz, 3800W, EU plug, Non-stick detachable food basket, available dishwasher cleaning, and easy to clean, High-speed air circulation technology frying delicious food, not greasy, Tastiest food and snacks without oil, Up to 80% less fat, Adjust the time and temp. control, Multiple functions of fry, grill, bake, or toast., 1500W Max heatwave technology, Air fry, roast, bake, grill, and reheat foods, Color Black",
    "image": "http://127.0.0.1:5501/Img/hf1.jpg",
}, {
    "id": 97,
    "title": "Haier Air FryerI-Master Series 5 HAF5TWA3 001",
    "Price": " 30,000.",
    "keyFeatures": "1 Years Warranty Only, 4L Air Fryer, 220V, 50Hz, 3800W, EU plug, Non-stick detachable food basket, available dishwasher cleaning, and easy to clean, High-speed air circulation technology frying delicious food, not greasy, Tastiest food and snacks without oil, Up to 80% less fat, Adjust the time and temp. control, Multiple functions of fry, grill, bake, or toast., 1500W Max heatwave technology, Air fry, roast, bake, grill, and reheat foods, Color Blackk",
    "image": "http://127.0.0.1:5501/Img/hf2.webp",
}, {
    "id": 98,
    "title": "Haier Air Fryer I-Master Series 5 Multi-Air Fryer XXL 7L",
    "Price": " 35,000.",
    "keyFeatures": "1 Years Warranty Only, 7L Air Fryer, 220V, 50Hz, 3800W, EU plug, Non-stick detachable food basket, available dishwasher cleaning, and easy to clean, High-speed air circulation technology frying delicious food, not greasy, Tastiest food and snacks without oil, Up to 80% less fat, Adjust the time and temp. control, Multiple functions of fry, grill, bake, or toast., 1500W Max heatwave technology, Air fry, roast, bake, grill, and reheat foods, Color Black",
    "image": "http://127.0.0.1:5501/Img/hf3.webp",
}, {
    "id": 99,
    "title": "Haier Air Fryer, I-Master Series 5, 6-in-1 with Touch",
    "Price": " 25,000.",
    "keyFeatures": "1 Years Warranty Only, 5L Air Fryer, 220V, 50Hz, 3800W, EU plug, Non-stick detachable food basket, available dishwasher cleaning, and easy to clean, High-speed air circulation technology frying delicious food, not greasy, Tastiest food and snacks without oil, Up to 80% less fat, Adjust the time and temp. control, Multiple functions of fry, grill, bake, or toast., 1500W Max heatwave technology, Air fry, roast, bake, grill, and reheat foods, Color Gray",
    "image": "http://127.0.0.1:5501/Img/hf4.jpg",
}, {
    "id": 100,
    "title": "Haier HAF40W 4Liter Air Fryer",
    "Price": " 22,500.",
    "keyFeatures": "1 Years Warranty Only, 4L Air Fryer, 220V, 50Hz, 3800W, EU plug, Non-stick detachable food basket, available dishwasher cleaning, and easy to clean, High-speed air circulation technology frying delicious food, not greasy, Tastiest food and snacks without oil, Up to 80% less fat, Adjust the time and temp. control, Multiple functions of fry, grill, bake, or toast., 1500W Max heatwave technology, Air fry, roast, bake, grill, and reheat foods, Color Black",
    "image": "http://127.0.0.1:5501/Img/hf5.jpg",
}, {
    "id": 101,
    "title": "Samsung 65″ Q70A QLED 4K Smart TV",
    "Price": " 285,500.",
    "keyFeatures": "Boost up your gaming Picture, Intelligence behind the glorious picture and sound, Optimized backlight color tone for enhanced contrast, Quantum Processor 4K, Dual LED, 100% Color Volume with Quantum Dot, Motion Xcelerator Turbo+ (FreeSync, Variable Refresh Rate), HDMI 2.1 (120 FPS), Auto Low Latency Mode (ALLM), Multi View",
    "image": "http://127.0.0.1:5501/Img/TV1.webp",
}, {
    "id": 102,
    "title": "TCL Smart LED 43S5400",
    "Price": " 80,999.",
    "keyFeatures": "FHD, HDR 10, Metallic Bezel-less, Google TV, Big Memory + Massive Content, Dolby Audio, HDMI * 2, WIFI, Bluetooth 5.0, 1 Year Warranty",
    "image": "http://127.0.0.1:5501/Img/TV2.jpg",
}, {
    "id": 103,
    "title": "HAIER 55K800UX LED 55″ Smart TV",
    "Price": " 123,500.",
    "keyFeatures": "Screen Size: 55″, Resolution: 4K UHD, Category: Google TV, Sound: 24 Watts, Processor: Crystal Processor 4K, Refresh rate: 60 Hz, HDMI ports: 3 (HDMI 2.1 support), AI upscaling: Yes, Smart hub: Yes, AirSlim design: Yes (26 mm thin)",
    "image": "http://127.0.0.1:5501/Img/TV3.jpg",
}, {
    "id": 104,
    "title": "Hisense 50A6H Smart Series 50-Inch Class 4K UHD Google TV",
    "Price": " 122,999.",
    "keyFeatures": "Dolby Vision™, HDR and HDR10, 4K Ultra High Definition, Google Assistant, Chromecast Built-In, Game Mode, Sports Mode, Google TV, Bluetooth™ Connectivity, Voice Remote",
    "image": "http://127.0.0.1:5501/Img/TV4.jpg",
}, {
    "id": 105,
    "title": "Panasonic Smart LED GX706M 65",
    "Price": " 225,999.",
    "keyFeatures": "Panel : 4K ULTRA HD IPS LED LCD, Bright Panel : Super Bright Panel Plus, Screen Resolution : 3,840 (W) x 2,160 (H), Signal Processor : Quad core 1.2GHz, Multi HDR Support*² : HDR10, Dolby System : Dolby Audio, Surround : DTS surround sound, Wireless LAN Built-in : Y, USB : 2(2 side; USB 2.0 x 1), LAN Port (Ethernet) : 1",
    "image": "http://127.0.0.1:5501/Img/TV5.jpg",
}, {
    "id": 106,
    "title": "LG 55 inch LED 4K Smart UHD TV 55nano75upa",
    "Price": " 187,999.",
    "keyFeatures": "Real 4K NanoCell Display, Quad Core Processor 4K, Display Resolution 4K Ultra HD (3,840 x 2,160), Refresh Rate TruMotion 120 (60Hz Native), Upscaling 4K Upscaling, Display Type Real 4K NanoCell Display, HDR: Active HDR (HDR10, HLG), Power Consumption 90W, LG ThinQ® AI, Intelligent Voice Recognition",
    "image": "http://127.0.0.1:5501/Img/th1.jpg",
}, {
    "id": 107,
    "title": "VION SMART LED 40FHDKA",
    "Price": " 67,499.",
    "keyFeatures": "Warranty: 1 Years, Weight 2250 kg, Category Type LED TV, 1080p@30fps, Brand VON LED TV 40INCH | 40FHDKA",
    "image": "http://127.0.0.1:5501/Img/th2.jpeg",
}, {
    "id": 108,
    "title": "Ecostar LED TV 50 inches Smart 4K | CX-50UD962",
    "Price": " 114,900.",
    "keyFeatures": "Warranty: 1 Years, HDMI 2.0 (Supports ARC) 3, Dimension (W x D x H) mm TV With Stand 1126x227x713mm, Screen Size 50, 64/128GB, Display 3840*2160, AC 100-240V, Smart 4K TV, Colors: Black, 50 inches",
    "image": "http://127.0.0.1:5501/Img/th3.jpeg",
}, {
    "id": 109,
    "title": "Sony 75Inch LED TV",
    "Price": " 500,000.",
    "keyFeatures": "Warranty: 1 Years, 75 Inch, Smart TV, 4K, LED TV, KD-75X80J-SN, HDMI 2, Colors: Black",
    "image": "http://127.0.0.1:5501/Img/th4.jpg",
}, {
    "id": 110,
    "title": "TCL 50 inches Smart QLED TV",
    "Price": " 156,900.",
    "keyFeatures": "Warranty: 1 Years, GOOGLE TV, 60MZ MEMC, AI X IOT, HDR 10, HLG, DOLBY VISION, WIDE VEIWING ANGLE, GAME PICTURE MODE",
    "image": "http://127.0.0.1:5501/Img/th5.webp",
}, {
    "id": 111,
    "title": "Realme Narzo 50A Prime Android 11, Realme UI 2.0",
    "Price": " 23,799.",
    "keyFeatures": "Warranty: 1 Years, Dual SIM, Li-Po 5000 mAh, non-removable, 1080p@30fps, 64/128GB, Unisoc Tiger T612, Mali-G57, 50 MP + 2 MP + 0.3 MP (Camera), Colors: Black or Blue (Subject to availability), 1080 x 2408 pixels",
    "image": "http://127.0.0.1:5501/Img/ph1.webp",
}, {
    "id": 112,
    "title": "Xiaomi Redmi A3 Android 14 (Go edition), MIUI",
    "Price": " 20,499.",
    "keyFeatures": "Warranty: 1 Years, 5000 mAh, 8MP AI Dual Camera, 1080p@30fps, PowerVR GE8320, Corning Gorilla Glass 3, Dual SIM, 6.71 Inches, Colors: midnight Black, Fprest Green and Sky Blue(Subject to availability), 6.71 Inches screen",
    "image": "http://127.0.0.1:5501/Img/ph2.webp",
}, {
    "id": 113,
    "title": "TECNO SPARK Go 2024 64GB ROM+8GB RAM*(4GB+4GB Extended) 6.6 HD+ Hole PTA APPROVED OFFICIAL BRAND WARRANTY",
    "Price": " 21,650.",
    "keyFeatures": "Mystery White / Alpenglow Gold / Magic Skin / Gravity Black, Android T-Go, 64GB ROM+8GB RAM*(4GB+4GB Extended), Composite Material: 163.69x75.6x8.55mm, Front: 8MP, Front Dual Flash, 5000mAh(typ)10W ChargeType-C, Dual Speakers, Rear: 13MP+AI-CAM, Rear Dual Flash, 4G, Software Gyroscope",
    "image": "http://127.0.0.1:5501/Img/ph3.PNG",
}, {
    "id": 114,
    "title": "VGOTEL New 24 RAM 4 GB ROM 128 Front Camera 13 MP Back Camera 50 MP Battery Type 5000 mAh",
    "Price": " 19,980.",
    "keyFeatures": "Screen 6.582 Inches, Hybrid dual sim, 128GB RAM, LED flash, Warranty: 1 Years, 5000mAh, Android 13, Mediatek Helio G35, Colors: Black or Sky Blue (Subject to availability), IPS LCD",
    "image": "http://127.0.0.1:5501/Img/ph4.PNG",
}, {
    "id": 115,
    "title": "Tecno Spark 20 Pro+ 8GB RAM + 256GB Smartphone, Magic Green",
    "Price": " 56,000.",
    "keyFeatures": "Warranty: 1 Years, Dual Sim, Dual Standby (Nano-SIM), Temporal Orbits, Lunar Frost, Radiant Starstream, Magic Skin 2.0 Green, Octa-core (2 x 2.2 GHz Cortex-A76 + 6 x 2.0 GHz Cortex-A55), AMOLED Capacitive Touchscreen, 16M Colors, Multitouch, Dual Camera: 108 MP + 2 MP (macro lens), Quad LED Flash, Wi-Fi 802.11 a/b/g/n/ac, dual-band, Accelerometer, Compass, Fingerprint (under display, optical), Gyro, Proximity, Glass front, plastic back, plastic frame, IP53, dust and splash resistant, Document viewer, Photo/video editor, Fast charging 33W wired",
    "image": "http://127.0.0.1:5501/Img/ph5.jpg",
}, {
    "id": 116,
    "title": "Xiaomi Redmi Note 13 Pro+ 5G, 12GB RAM+ 512GB Smartphone, White",
    "Price": " 139,999.",
    "keyFeatures": "Warranty: 1 Years, Nano-SIM, eSIM or Dual SIM (Nano-SIM, dual stand-by), 6.67 inches size, Internal 512GB 8GB RAM, Wi-Fi Direct, Fingerprint (under display, optical), accelerometer, gyro, proximity, compass, Yes, with stereo speakers, 4K@24/30fps, 1080p@30/60/120fps, gyro-EIS, Colors: Black or Silver (Subject to availability), Glass front (Gorilla Glass Victus), glass back or silicone polymer back (eco leather)",
    "image": "http://127.0.0.1:5501/Img/ph6.webp",
}, {
    "id": 117,
    "title": "Apple iPhone 15 Pro Max",
    "Price": " 349,999.",
    "keyFeatures": "Warranty: 1 Years, 256GB,512GB,1TB Storage, 48MP Main, 12MP Ultra Wide, and 12MP Telephoto, Up to 29 hours video playback, 6.7 Inches , 5G Support, No Finger Print., Video playback Up to 23 hours, Face ID LiDAR Scanner Barometer, Type to Siri, Colors: Black or Silver, Dual eSIM",
    "image": "http://127.0.0.1:5501/Img/ph7.jpg",
}, {
    "id": 118,
    "title": "Apple iPhone 11 128GB PTA Approved",
    "Price": " 149,999.",
    "keyFeatures": "Fast Battery Charging 18W: 50% in 30 min, iOS 13, Scratch-Resistant Glass, Oleophobic Coating, Face ID, accelerometer, gyro, proximity, compass, barometer, 828 x 1792 pixels Screen, 12 Mega Pixel (TOF 3D Camera), 12 Mega Pixel 26mm (Wide), 12 Mega Pixel 13mm (Ultrawide), Third Generation Neural Engine, Apple A13 Bionic (7 nm+), Warranty: 1 Years",
    "image": "http://127.0.0.1:5501/Img/ph8.jpg",
}, {
    "id": 119,
    "title": "OPPO Reno 11 F",
    "Price": " 79,999.",
    "keyFeatures": "Dual SIM (Nano-SIM, dual stand-by), Android 14, ColorOS 14, 256GB 8GB RAM, 4K@30fps, 1080p@30/60/120/480fps, gyro-EIS, Wi-Fi 802.11 a/b/g/n/ac/6, dual-band, 5000 mAh, non-removable, Palm Green, Ocean Blue, Coral Purple, 6.7 inches, 108.0 cm, 1 Year Warranty, Stainless steel tanks for Health & Hygiene",
    "image": "http://127.0.0.1:5501/Img/ph9.webp",
}, {
    "id": 120,
    "title": "Samsung Galaxy S24 Ultra",
    "Price": " 369,700.",
    "keyFeatures": "Warranty: 1 Years, Nano-SIM and eSIM/ Dual eSIM or Dual SIM, Dynamic LTPO AMOLED 2X, 120Hz, HDR10+, 2600 nits (peak), 256GB 12GB RAM, 512GB 12GB RAM, 1TB 12GB RAM, Qualcomm SM8650-AC Snapdragon 8 Gen 3 (4 nm), 4K@30/60fps, 1080p@30fps, Dual video call, Auto-HDR, HDR10+, Titanium Black, Titanium Gray, Titanium Violet, Titanium Yellow, Titanium Blue, Titanium Green, Titanium Orange, Corning Gorilla Armor, Glass front (Corning Gorilla Armor), glass back (Corning Gorilla Armor), titanium frame (grade 2)",
    "image": "http://127.0.0.1:5501/Img/ph10.webp",
}, {
    "id": 121,
    "title": "Lenovo Smart Tab M10 FHD Plus (2nd Gen) with Google Assistant - 4GB LPDDR4 - 128GB eMMC",
    "Price": " 113,799.",
    "keyFeatures": "Warranty: 1 Years, Memory: 4 GB LPDDR4X (Soldered), Hard Drive: 128 GB eMMC, Processor: MediaTek Helio P22T Tab, Octa-Core, 4 x A53 2.3 GHz, 4 x A53 1.8 GHz, Operating System: Android 9 Pie, Display Type: 10.3 FHD (1920 x 1200) IPS, TDDI, touchscreen, 220 PPI, 330 nits, Bluetooth: Bluetooth 5.0, Wireless: 802.11 a/b/g/n/ac (1 x 1), Camera: Rear: 8 MP auto-focus, Front: 5 MP fixed-focus, Battery: Li-Polymer",
    "image": "http://127.0.0.1:5501/Img/tb1.jpg",
}, {
    "id": 122,
    "title": "Lenovo Tab M10 Plus (3rd Gen) 10 Tablet, 128GB Storage, 4GB Memory, Android 12, FHD Display",
    "Price": " 86,001.",
    "keyFeatures": "Processor Brand MediaTek, Dual SIM, Processor Type ARM (Cortex A75 Dual-core (2 Core) 2GHz + Cortex A55 Hexa-core (6 Core) 1.8GHz), Memory Card Type Micro SDXC, Micro SD, Inputs & Outputs USB Type-C, Wireless Technology Bluetooth, 802.11ac, RAM Memory 4 GB, 50 MP + 2 MP + 0.3 MP (Camera), Operating System Android 12, Assembled Product Weight 1.04 pounds (0.47 kg)",
    "image": "http://127.0.0.1:5501/Img/tb2.webp",
}, {
    "id": 123,
    "title": "T60 Tablet",
    "Price": " 60,999.",
    "keyFeatures": "T60 boasts a sleek 12-inch screen, Dual SIM, 558g with a thickness of 7.8mm, T60 is powered by the UNISOC Tiger, 8000mAh battery, Unisoc Tiger T612, Max Sensory Intelligence, 50 MP + 2 MP + 0.3 MP (Camera), Colors: Black or Blue (Subject to availability), Featuring a 13MP rear autofocus camera",
    "image": "http://127.0.0.1:5501/Img/tb3.webp",
}, {
    "id": 124,
    "title": "Android Tablet Pritom 10.1 Android 10 Tablet, 2GB RAM, 32GB ROM, Quad Core Processor, HD IPS Screen, 2.0 Front + 8.0 MP Rear Camera, Wi-Fi, Bluetooth, GPS, Tablet PC(Black)",
    "Price": " 42,840.",
    "keyFeatures": "Warranty: 1 Years, Screen 10 Inches, 2 GB RAM, 32 GB Hard Drive, 64/128GB, 9.6 x 6.9 x 0.3 inches, 1 Lithium Polymer batteries required. (included), 50 MP + 2 MP + 0.3 MP (Camera), Colors: Black or Blue (Subject to availability), 802.11bgn",
    "image": "http://127.0.0.1:5501/Img/tb4.jpg",
}, {
    "id": 125,
    "title": "SAMSUNG Galaxy Tab S6 Lite 10.4 64GB WiFi Android Tablet w/ S Pen Included, Slim Metal Design, Crystal Clear Display, Dual Speakers, Long Lasting Battery, SM-P610NZAAXAR, Oxford Gray",
    "Price": " 56,800.",
    "keyFeatures": "Warranty: 1 Years, Dual SIM, 10.4 screen, 2000 x 1200 (WUXGA+) TFT, 64/128GB, Dual + AKG + Dolby Atmos, Exynos 9611, 50 MP + 2 MP + 0.3 MP (Camera), Colors: Black or Blue (Subject to availability), microSD up to 1TB",
    "image": "http://127.0.0.1:5501/Img/tb5.jpg",
}, {
    "id": 126,
    "title": "Okaysea Tablet 10.1 Inch Quad-Core 32GB Android 12 IPS HD Display 5000mAh Tablets (Gray)",
    "Price": " 18,999.",
    "keyFeatures": "Warranty: 1 Years, 24.59 x 16.28 x 0.79 cm; 830 g, Hard Drive: 128 GB eMMC, 1 Lithium Ion batteries required., Gaming tablet, 10.1 Inches, Bluetooth: Bluetooth 5.0, 1280 x 800 pixels, Camera: Rear: 8 MP auto-focus, Front: 5 MP fixed-focus, Batteries packed with equipment",
    "image": "http://127.0.0.1:5501/Img/tbh1.jpg",
}, {
    "id": 127,
    "title": "Samsung Galaxy Tab A9 WiFi Android Tablet, 8.7 Large Display, 4GB RAM, 64GB Storage, Graphite (UAE Version)",
    "Price": " 30,000.",
    "keyFeatures": "802.11n, 802.11b, 802.11a, 802.11ac, 802.11g, 800x1340 Pixels, Hard Drive: 128 GB eMMC, 5000 Milliampere Hour (mAh), Batteries contained in equipment, 329 g, Bluetooth: Bluetooth 5.0, Wi-Fi, Camera: Rear: 8 MP auto-focus, Front: 5 MP fixed-focus, 5000 Milliampere Hour (mAh)",
    "image": "http://127.0.0.1:5501/Img/tbh3.jpg",
}, {
    "id": 128,
    "title": "X-Prime A15 Max 10.1 HD Display Android 13 Slim Smart Tablet PC with Keyboard, Mouse, Dual SIM, 5G Network, Wifi Tablet, 8GB RAM 256GB ROM, Dual Camera, Google Meet and Zoom Supported (Grey)",
    "Price": " 32,000.",
    "keyFeatures": "Warranty: 1 Years, 3000x1440 Pixels, Hard Drive: 128 GB eMMC, Processor: MediaTek Helio P22T Tab, Octa-Core, 4 x A53 2.3 GHz, 4 x A53 1.8 GHz, Batteries contained in equipment, Android 13, Bluetooth: Bluetooth 5.0, 5 Watt Hours, Camera: Rear: 8 MP auto-focus, Front: 5 MP fixed-focus, 1.34 Kilograms",
    "image": "http://127.0.0.1:5501/Img/tbh4.jpg",
}, {
    "id": 129,
    "title": "Umiio 10.1 Android Smart Tablet PC Dual SIM 5G Wifi 6GB RAM 128GB ROM Game and Music A10 Pro Kids Tab (Gold)",
    "Price": " 21,000.",
    "keyFeatures": "Warranty: 1 Years, Memory: 4 GB LPDDR4X (Soldered), 27 x 18.8 x 5 cm; 920 g, Processor: MediaTek Helio P22T Tab, Octa-Core, 4 x A53 2.3 GHz, 4 x A53 1.8 GHz, Operating System: Android 9 Pie, Display Type: 10.3 FHD (1920 x 1200) IPS, TDDI, touchscreen, 220 PPI, 330 nits, 1 Lithium Polymer batteries required. (included), Wireless: 802.11 a/b/g/n/ac (1 x 1), Bluetooth, Wi-Fi, Battery: Li-Polymer",
    "image": "http://127.0.0.1:5501/Img/tbh2.jpg",
}, {
    "id": 130,
    "title": "Lenovo Smart Tab M10 FHD Plus (2nd Gen) with Google Assistant - 4GB LPDDR4 - 128GB eMMC",
    "Price": " 113,799.",
    "keyFeatures": "Warranty: 1 Years, Memory: 4 GB LPDDR4X (Soldered), Hard Drive: 128 GB eMMC, Processor: MediaTek Helio P22T Tab, Octa-Core, 4 x A53 2.3 GHz, 4 x A53 1.8 GHz, Operating System: Android 9 Pie, Display Type: 10.3 FHD (1920 x 1200) IPS, TDDI, touchscreen, 220 PPI, 330 nits, Bluetooth: Bluetooth 5.0, Wireless: 802.11 a/b/g/n/ac (1 x 1), Camera: Rear: 8 MP auto-focus, Front: 5 MP fixed-focus, Battery: Li-Polymer",
    "image": "http://127.0.0.1:5501/Img/tb1.jpg",
}, {
    "id": 131,
    "title": "Lenovo IdeaPad 3",
    "Price": " 161,990.",
    "keyFeatures": "1-year official brand warranty, Intel Core i7-1165G7, Italian spare parts, Made in Turkey, Integrated Intel Iris Xe Graphics, Full safety system, 4GB Soldered DDR4-3200 + 4GB SO-DIMM DDR4-3200, 1TB HDD 5400rpm 2.5″, size : 90 cm, 15.6″ FHD (1920×1080) TN 250nits Anti-glare, 4C / 8T, 2.8 / 4.7GHz, 12MB, Color Silver",
    "image": "http://127.0.0.1:5501/Img/Lt1.jpg",
}, {
    "id": 132,
    "title": "ASUS TUF GAMING F15 FX507VV-LP299 | Intel Core i7 13620H, 8GB RAM, 512GB SSD, 15.6″ FHD 144Hz, 8GB NVIDIA RTX 4060, DOS, RGB Backlit Keyboard, Gray",
    "Price": " 379,999.",
    "keyFeatures": "1-year official brand warranty, Intel Core i7 13620H Processor, 512GB M.2 SSD, DOS, Grey, Backlit Keyboard, 2 Year Warranty., 15.6″ FHD IPS 14Hz, 8GB Nvidia RTX 4060, 8GB DDR5-4800 SO-DIMM, Color Black",
    "image": "http://127.0.0.1:5501/Img/Lt2.webp",
}, {
    "id": 133,
    "title": "Alienware x14 R1 14.0″ 144Hz FHD Gaming Laptop – Intel Core i7 – 16GB 5200MHz Memory – NVIDIA GeForce RTX 3060 – 512GB SSD NVMe (Lunar Light)",
    "Price": " 439,999.",
    "keyFeatures": "High-Performance Intel Core i7 Processor, Immersive 144Hz FHD Display, NVIDIA GeForce RTX 3060 Graphics, 16GB 5200MHz Memory, Blazing-Fast 512GB SSD NVMe, Lunar Light Design, Portable Gaming Powerhouse, Alienware Innovation, Your Gaming Arsenal Awaits, Experience Gaming Like Never Before, Color Black",
    "image": "http://127.0.0.1:5501/Img/Lt3.jpg",
}, {
    "id": 134,
    "title": "HP Laptop EQ2180AU 15.6 Inches AMD Ryzen 5 (8GB RAM - 512GBSSD)",
    "Price": " 194,000.",
    "keyFeatures": "Processor Type AMD® Ryzen 5 5500U Hexa-Core Processor, Processor Speed 2.1 GHz up to 4.0 GHz max boost clock, 8 MB L3 cache, 6 cores, 12 threads, Camera HP True Vision 720p HD camera with integrated dual array digital microphones, Graphics Memory AMD Radeon™ Graphics, RAM 8 GB, Internal Memory 512 GB, Screen Resolution 1920x1080, Screen Size 15.6, Operating System Genuine Windows 11 Home, Weight 1.69 kg, USB 1 SuperSpeed USB Type-C® 5Gbps signaling rate; 2 SuperSpeed USB Type-A 5Gbps signaling rate, Bluetooth Bluetooth 5.0, Generation AMD",
    "image": "http://127.0.0.1:5501/Img/Lt4.jpg",
}, {
    "id": 135,
    "title": "HP 15s-FQ5297 Core i7 12th Generation Laptop",
    "Price": " 199,000.",
    "keyFeatures": "Processor: 12th Gen Intel Core i7-1265G7 quad-core processor, Graphics: Intel Iris Xe Graphics, Display: 15.6-inch diagonal FHD IPS anti-glare micro-edge WLED-backlit display (1920 x 1080), Memory: 8 GB DDR4-3200 SDRAM (2 x 8 GB), Storage: 512 GB PCIe NVMe M.2 SSD, Operating System: Windows 10 Home, Ports: 1 SuperSpeed USB Type-C 10Gbps signaling rate (USB Power Delivery, DisplayPort 1.4, HP Sleep and Charge), 2 SuperSpeed, USB Type-A 5Gbps signaling rate, 1 HDMI 2.0, 1 AC smart pin, 1 headphone/microphone combo, Bluetooth Yes",
    "image": "http://127.0.0.1:5501/Img/lt5.jpg",
}, {
    "id": 136,
    "title": "HP Probook 440 G10 | 13th Generation, Intel Core i5-1335U",
    "Price": " 185,000.",
    "keyFeatures": "Processor family 13th Generation Intel Core i5, Processor Intel® Core™ i5-1335U (up to 4.6 GHz with Intel® Turbo Boost Technology, 12 MB L3 cache, 10 cores, 12 threads), Graphics Integrated, Intel® Iris® Xᵉ Graphics, Memory 8 GB DDR4-3200 MHz RAM, Display 39.6 cm (15.6″) diagonal, FHD (1,280 x 720), IPS, narrow bezel, anti-glare, 250 nits, 45% NTSC, Weight Starting at 1.74 kg (Weight will vary by configuration.), Power HP Smart 65 W External AC power adapter 8, Fingerprint reader Yes, Wireless Realtek RTL8852AE Wi-Fi 6 (2×2) and Bluetooth®️ 5.2 combo",
    "image": "http://127.0.0.1:5501/Img/lt6.jpg",
}, {
    "id": 137,
    "title": "HP PROBOOK 430 G4 USED LAPTOP CORE I5 7TH GENERATION 8 GB RAM 500 GB HDD 13.3″ AND 15",
    "Price": " 65,000.",
    "keyFeatures": "Processor Type 7th Generation Intel Core i5-7200U Processor (2 Cores – 4 Threads), Processor Speed 2.5 GHz Turbo Boost 3.1 (3 MB Cache, Kaby lake), Installed RAM 8 GB, Screen surface Diagonal HD anti-glare LED-backlit, Screen resolution 1366×768, Weight Starting at 1.49 kg, Operating system (Primary) Windows 10 Pro 64 – HP recommends Windows 10 Pro, Graphics processor Chipset is integrated with processor, Hard drive speed 7200 RPM, Weight Starting at 1.49 kg",
    "image": "http://127.0.0.1:5501/Img/lt7.webp",
}, {
    "id": 138,
    "title": "Dell Latitude E5470 Core i5 6440HQ 4GB Ram 500GB Hard Drive 14″ Full HD Display",
    "Price": " 64,000.",
    "keyFeatures": "GENERATION 6th Generation, PROCESSOR TYPE Intel Core i5, HARD DRIVE CAPACITY 500 GB, SCREEN SIZE 14″ Display, SCREEN RESOLUTION 1920 x 1080, USB VERSION USB 2.0, USB 3.0, BATTERY 4 Cell, SOLID STATE DRIVE (SSD) No SSD, TOUCH SCREEN No, OPTICAL DRIVE No, Color Black",
    "image": "http://127.0.0.1:5501/Img/lt8.webp",
}, {
    "id": 139,
    "title": "DELL LATITUDE E7280 USED LAPTOP CORE I5 7TH GENERATION 8GB RAM 256GB SSD 12.5″ AND 15",
    "Price": " 50,000.",
    "keyFeatures": "Processor Ci5 7th Generation, Processor Speed 7300U Core i5 2.6GHz upto 3.6GHz, Screen Resolution 1366 x 768 HD LED, Graphics Card Intel Integrated Graphics, Max Ram 32GB, SSD 256GB, Screen Resolution 1366 x 768 HD LED, Screen Size 12.5 inch, Operating System Genuine Windows 10 Home, Graphics Card Intel Integrated Graphics, Graphics Card Details Intel HD Graphics 620, Bluetooth Bluetooth 5.0, Graphics Card Memory System Shared",
    "image": "http://127.0.0.1:5501/Img/lt9.webp",
}, {
    "id": 140,
    "title": "Dell Latitude 3420 Core i7 11th Generation",
    "Price": " 220,000.",
    "keyFeatures": "Device Type Netbook, Dimensions 226 x 326 x 17.6 mm, Warranty 1 year Warranty, Resolution 1366 x 768 pixels, Size 14 inches, USB Ports 1 x USB Type-C, 2 x USB 3.0, 1 x USB 2.0, GPU Intel UHD Graphics, Maximum RAM Supported Upto 32 GB, RAM 8 GB, Hard Disk Speed 7200 RPM, Hard Disk Capacity 500 GB, Battery 3 Cell Battery, Speed 2.4 GHz, Quad Core Turbo Boost Upto 4.2 GHz",
    "image": "http://127.0.0.1:5501/Img/lt10.jpg",
}, {
    "id": 141,
    "title": "Macbook air retina M1 2020 Narzo 50A Prime",
    "Price": " 262,799.",
    "keyFeatures": "13-3 Inches LED display, 1.1GHz dual-core Intel Core i3 processor, Scale resolution of 1680 by 1050, 1440 by 900, and 1024 by 640, 8GB memory which is configurable to 16GB UNIFIED MEMORY, 256GB SSD, which is configurable to 512GB, Battery power up to 11 hours, 720p camera, USB 3.1 generation 2, Stereo speakers for powerful sound setup, 3.3 mm headphones portal, Built-in Apps for convenient use, Truetone technology",
    "image": "http://127.0.0.1:5501/Img/mac1.jpg",
}, {
    "id": 142,
    "title": "Apple MacBook Air 13 MGN63",
    "Price": " 248,900.",
    "keyFeatures": "Screen size 13.3 Retina Display With True Tone & IPS Technology, Generation Apple M1 Chip, Processor Type Apple M1 Chip, Processor Speed 8-core CPU with 4 perform­ance cores and 4 efficiency cores 7-core GPU 16-core Neural Engine, 8GB memory which is configurable to 16GB UNIFIED MEMORY, 256GB SSD, which is configurable to 512GB, Battery power up to 11 hours, Fingerprint Reader Touch ID sensor, Bluetooth Bluetooth 5.0 wireless technology, Camera 720p FaceTime HD camera, Color Space Gray, Screen resolution 2560-by-1600, Truetone technology",
    "image": "http://127.0.0.1:5501/Img/mac2.jpg",
}, {
    "id": 143,
    "title": "Apple Macbook Air 15 MQKW3",
    "Price": " 342,900.",
    "keyFeatures": "Screen size 15.3 IPS Retina Display, Generation Apple M2 Chip, Processor Type Apple M2 Chip, Processor Speed 8 - Core CPU, 10 - Core GPU, 8GB memory which is configurable to 16GB UNIFIED MEMORY, 256GB SSD, which is configurable to 512GB, Battery power up to 11 hours, Fingerprint Reader Touch ID sensor, Type 802.11ax (Wi-Fi 6), Camera 720p FaceTime HD camera, USB Total USB Type C 2 Ports, Screen resolution 2880 x 1864, Truetone technology",
    "image": "http://127.0.0.1:5501/Img/mac3.jfif",
}, {
    "id": 144,
    "title": "Apple MacBook Air 13 MRXN3",
    "Price": " 354,900.",
    "keyFeatures": "13.6-inch (diagonal) LED-backlit display with IPS technology, 2560-by-1664 native resolution at 224 pixels per inch, 500 Nits, Generation Apple M3 Chip, Processor Type Apple M3 Chip, Processor Speed 8-core CPU with 4 performance cores and 4 efficiency cores, 8-core GPU Hardware-accelerated ray tracing 16-core Neural Engine, 8GB memory which is configurable to 16GB UNIFIED MEMORY, 256GB SSD, which is configurable to 512GB, Battery power up to 11 hours, Fingerprint Reader Touch ID sensor, Bluetooth 5.3, Camera 1080p FaceTime HD camera, USB Total Two Thunderbolt / USB 4 ports, Screen resolution 2560 x 1664, Truetone technology",
    "image": "http://127.0.0.1:5501/Img/mac4.jfif",
}, {
    "id": 145,
    "title": "Apple MacBook Air 13 MRXV3",
    "Price": " 354,900.",
    "keyFeatures": "13.6-inch (diagonal) LED-backlit display with IPS technology, 2560-by-1664 native resolution at 224 pixels per inch, 500 Nits, Generation Apple M3 Chip, Processor Type Apple M3 Chip, Processor Speed 8-core CPU with 4 performance cores and 4 efficiency cores, 8-core GPU Hardware-accelerated ray tracing 16-core Neural Engine, 8GB memory which is configurable to 16GB UNIFIED MEMORY, 256GB SSD, which is configurable to 512GB, Battery power up to 11 hours, Fingerprint Reader Touch ID sensor, Bluetooth 5.3, Camera 1080p FaceTime HD camera, USB Total Two Thunderbolt / USB 4 ports, Screen resolution 2560 x 1664, Truetone technology",
    "image": "http://127.0.0.1:5501/Img/mac4.jfif",
}, {
    "id": 146,
    "title": "Apple MacBook Air 15 M3 MXD33",
    "Price": " 414,999.",
    "keyFeatures": "13.6-inch (diagonal) LED-backlit display with IPS technology, 2560-by-1664 native resolution at 224 pixels per inch, 500 Nits, Generation Apple M3 Chip, Processor Type Apple M3 Chip, 8 Core CPU with 4 performance Cores and 4 efficiency Cores, 8GB memory which is configurable to 16GB UNIFIED MEMORY, 256GB SSD, which is configurable to 512GB, Battery power up to 18 hours, Fingerprint Reader Touch ID sensor, Dimensions (WxHxD) Height: 0.45 inch (1.15 cm) Width: 13.40 inches (34.04 cm) Depth: 9.35 inches (23.76 cm), Camera 1080p FaceTime HD camera, USB Total Two Thunderbolt / USB 4 ports, Screen resolution 2880 x 1864, Truetone technology",
    "image": "http://127.0.0.1:5501/Img/mac6.jpg",
}, {
    "id": 147,
    "title": "Apple MacBook Air M2 MLY33",
    "Price": " 319,999.",
    "keyFeatures": "13 - inch (diagonal) LED-backlit display with IPS technology, 2560-by-1664 native resolution at 224 pixels per inch, 500 Nits, Generation Apple M2 Chip, Processor Type Apple M2 Chip, 4 Performance Cores and 4 Efficiency Cores, 8GB memory which is configurable to 16GB UNIFIED MEMORY, 256GB SSD, which is configurable to 512GB, Battery power up to 18 hours, Fingerprint Reader Touch ID sensor, Dimensions (WxHxD) Height: 0.45 inch (1.15 cm) Width: 13.40 inches (34.04 cm) Depth: 9.35 inches (23.76 cm), Camera 1080p FaceTime HD camera, USB Total Two Thunderbolt / USB 4 ports, Screen resolution 2560 x 1664, Liquid Retina display technology",
    "image": "http://127.0.0.1:5501/Img/mac7.jpg",
}, {
    "id": 148,
    "title": "Apple MacBook Air M2 MLY23",
    "Price": " 411,999.",
    "keyFeatures": "13.6-inch (diagonal) LED-backlit display with IPS technology (2560x1664) Native resolution at 224 pixels per inch with support for 1 billion colors 500 nits brightness True Tone technology, Generation Apple M2 Chip, Processor Type Apple M2 Chip, 8 Core CPU & 8 Core GPU 16 Core Neural Engine 100GB/s Memory Bandwidth, 8GB memory which is configurable to 16GB UNIFIED MEMORY, 256GB SSD, which is configurable to 512GB, Battery power up to 18 hours, Fingerprint Reader Touch ID sensor, Dimensions (WxHxD) Height: 0.45 inch (1.15 cm) Width: 13.40 inches (34.04 cm) Depth: 9.35 inches (23.76 cm), Camera 1080p FaceTime HD camera, USB Total Two Thunderbolt / USB 4 ports, Screen resolution 2560 x 1664, Liquid Retina display technology",
    "image": "http://127.0.0.1:5501/Img/mac8.webp",
}, {
    "id": 149,
    "title": "Apple MacBook Air M2 CTO",
    "Price": " 479,999.",
    "keyFeatures": "13-inch (diagonal) LED-backlit display with IPS technology (2560x1664) Native resolution at 224 pixels per inch with support for 1 billion colors 500 nits brightness True Tone technology, Generation Apple M2 Chip, Processor Type Apple M2 Chip, 4 Performance Cores and 4 Efficiency Cores, 8GB memory which is configurable to 16GB UNIFIED MEMORY, 256GB SSD, which is configurable to 512GB, Battery power up to 18 hours, Fingerprint Reader Touch ID sensor, Dimensions(WxHxD) Height: 0.45 inch(1.15 cm) Width: 13.40 inches(34.04 cm) Depth: 9.35 inches(23.76 cm), Camera 720p FaceTime HD camera, USB Total Two Thunderbolt / USB 4 ports, Screen resolution 2560 x 1600, Liquid Retina display technology",
    "image": "http://127.0.0.1:5501/Img/mac9.jpg",
}, {
    "id": 150,
    "title": "Apple MacBook Air M2 MQKP3",
    "Price": " 334,999.",
    "keyFeatures": "15-inch (diagonal) LED-backlit display with IPS technology (2560x1664) Native resolution at 224 pixels per inch with support for 1 billion colors 500 nits brightness True Tone technology, Generation Apple M2 Chip, Processor Type Apple M2 Chip, 8 Core CPU with 4 performance cores and 4 efficiency cores, 8GB memory which is configurable to 16GB UNIFIED MEMORY, 256GB SSD, which is configurable to 512GB, Battery power up to 18 hours, Fingerprint Reader Touch ID sensor, Dimensions (WxHxD) Height: 0.45 inch (1.15 cm) Width: 15.40 inches (34.04 cm) Depth: 9.35 inches (23.76 cm), Camera 1080p FaceTime HD camera, USB Total Two Thunderbolt / USB 4 ports, Screen resolution 2880 X 1864, Liquid Retina display technology",
    "image": "http://127.0.0.1:5501/Img/mac10.jpg",
}]
